const CLIENT_BASE=__CLIENT_BASE__;
let DATA=null;
const $=id=>document.getElementById(id);
const esc=value=>String(value==null?"":value).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const STATUS={HEALTHY:["正常","healthy"],WATCH:["关注","watch"],DEGRADED:["异常","degraded"],NOT_CALLED:["未调用","notcalled"]};
const SEVERITY={INFO:["提示","info"],WARNING:["预警","warning"],CRITICAL:["严重","critical"]};
const CASE_PHASE={NEEDS_INTAKE:["待识别","notcalled"],REASON_PROPOSED:["待确认原因","watch"],NEED_EVIDENCE:["待补资料","watch"],ASSESSED:["评估完成","healthy"]};
const METRIC_LABEL={assessments_total:"评估次数",requires_human_true:"需人工复核",requires_human_false:"无需人工复核",appeal_submitted:"申诉已提交",appeal_blocked:"申诉被阻断",prevention_risk_LOW:"低风险交易",prevention_risk_MEDIUM:"中风险交易",prevention_risk_HIGH:"高风险交易",explanation_source_MODEL:"辅助说明",explanation_source_FALLBACK:"规则说明"};
function badge(value,map=STATUS){const item=map[value]||[value,"notcalled"];return `<span class="badge ${item[1]}">${esc(item[0])}</span>`;}
document.querySelectorAll('.nav button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));button.classList.add('on');document.querySelectorAll('.view').forEach(x=>x.classList.remove('on'));$('view-'+button.dataset.view).classList.add('on');$('crumb').textContent=button.textContent;}));
function signalHtml(item){return `<div class="signal"><div class="signaltop">${badge(item.severity,SEVERITY)}<strong>${esc(item.title)}</strong></div><p>${esc(item.evidence)}</p><p class="advice">建议：${esc(item.recommendation)}</p></div>`;}
function endpointHtml(item){return `<div class="endpointmini"><div><div class="name">${esc(item.name)}</div><div class="meta">${esc(item.method)} ${esc(item.route)}</div></div>${badge(item.status)}</div>`;}
function renderOverview(){const d=DATA;if(!d)return;const status=STATUS[d.service_status.overall]||STATUS.NOT_CALLED;$('serviceValue').innerHTML=badge(d.service_status.overall);$('requestValue').textContent=d.request_summary.total;$('latencyValue').textContent=Math.round(d.request_summary.p95_latency_ms)+' ms';$('errorValue').textContent=d.request_summary.server_errors;$('overviewSignals').innerHTML=d.predictions.slice(0,3).map(signalHtml).join('');$('keyEndpoints').innerHTML=d.endpoints.slice(0,6).map(endpointHtml).join('');void status;}
function renderEndpoints(){if(!DATA)return;const selected=$('apiGroup').value;const rows=DATA.endpoints.filter(item=>selected==='ALL'||item.group===selected);$('endpointRows').innerHTML=rows.map(item=>`<tr><td><strong>${esc(item.name)}</strong><div class="route"><span class="method">${esc(item.method)}</span> ${esc(item.route)}</div></td><td>${badge(item.status)}</td><td class="num">${item.total}</td><td class="num">${item.client_errors}</td><td class="num">${item.server_errors}</td><td class="num">${(item.error_rate*100).toFixed(1)}%</td><td class="num">${Math.round(item.average_latency_ms)} ms</td><td class="num">${Math.round(item.p95_latency_ms)} ms</td><td class="num">${item.last_status||'—'}</td></tr>`).join('');}
function renderPredictions(){if(!DATA)return;$('allSignals').innerHTML=DATA.predictions.map(signalHtml).join('');$('predictionNote').textContent=DATA.prediction_disclaimer;}
function renderBusiness(){if(!DATA)return;const entries=Object.entries(DATA.business_counts);$('businessMetrics').innerHTML=entries.length?entries.map(([key,value])=>`<div class="businessitem"><span>${esc(METRIC_LABEL[key]||key)}</span><strong>${value}</strong></div>`).join(''):'<span class="empty">尚无业务数据；客户端产生评估或申诉后会自动出现。</span>';const cases=DATA.cases||[];const locale=window.oceanI18n.getLanguage()==='en'?'en-US':'zh-CN';$('caseRows').innerHTML=cases.length?cases.map(item=>{const phase=CASE_PHASE[item.phase]||[item.phase,'notcalled'];const created=item.created_at?new Date(item.created_at).toLocaleString(locale,{hour12:false}):'—';return `<tr><td><div class="case-id">${esc(item.case_id)}</div><div class="case-meta">案件库可重新读取</div></td><td>${esc(item.reason_label||item.reason_code||'待确认')}</td><td><span class="badge ${phase[1]}">${esc(phase[0])}</span></td><td class="num">${item.missing_count}</td><td class="num">${esc(created)}</td></tr>`;}).join(''):'<tr><td colspan="5" class="empty">当前案件库暂无有效实体；维护端不会生成占位案件。</td></tr>';}
function configureGroups(){const select=$('apiGroup');if(select.options.length>1)return;[...new Set(DATA.endpoints.map(item=>item.group))].forEach(group=>{const option=document.createElement('option');option.value=group;option.textContent=group;select.appendChild(option);});}
function loadOverview(){return OceanRequest.singleFlight('operations-overview',refreshOverview);}
async function refreshOverview(){const button=$('refresh');button.disabled=true;$('offline').classList.remove('on');try{const response=await OceanRequest.json(CLIENT_BASE+'/api/v1/admin/overview',{headers:{Accept:'application/json'}},15000);if(!response.ok)throw new Error('status');DATA=response.data;configureGroups();renderOverview();renderEndpoints();renderPredictions();renderBusiness();const locale=window.oceanI18n.getLanguage()==='en'?'en-US':'zh-CN';const stamp=new Date(DATA.generated_at).toLocaleTimeString(locale,{hour12:false});['updatedOverview','updatedApi','updatedPrediction','updatedBusiness'].forEach(id=>$(id).textContent='更新于 '+stamp);$('sourceHost').textContent=new URL(CLIENT_BASE).host;}catch(error){$('offline').classList.add('on');$('serviceValue').innerHTML=badge('DEGRADED');void error;}finally{button.disabled=false;}}
window.addEventListener('oceanpilot:languagechange',()=>{if(DATA){renderOverview();renderEndpoints();renderPredictions();renderBusiness();}window.oceanI18n.apply();});
loadOverview();setInterval(loadOverview,5000);
