from enum import StrEnum


class CaseType(StrEnum):
    PAYMENT_INCIDENT = "PAYMENT_INCIDENT"
    ONBOARDING_RECOMMENDATION = "ONBOARDING_RECOMMENDATION"


class CaseStatus(StrEnum):
    NEW = "NEW"
    NEED_INFO = "NEED_INFO"
    EVIDENCE_READY = "EVIDENCE_READY"
    DIAGNOSED = "DIAGNOSED"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class CaseCommand(StrEnum):
    CREATE_CASE = "CREATE_CASE"
    ADD_EVIDENCE = "ADD_EVIDENCE"
    DIAGNOSE = "DIAGNOSE"


class EvidenceAvailability(StrEnum):
    AVAILABLE = "AVAILABLE"
    CONFIRMED_UNAVAILABLE = "CONFIRMED_UNAVAILABLE"


class EvidenceValueType(StrEnum):
    STRING = "STRING"
    BOOLEAN = "BOOLEAN"
    DATETIME = "DATETIME"
    COUNTRY = "COUNTRY"
    CURRENCY = "CURRENCY"


class SourceType(StrEnum):
    MERCHANT = "MERCHANT"
    INTERNAL_OPERATOR = "INTERNAL_OPERATOR"
    SYSTEM_OF_RECORD = "SYSTEM_OF_RECORD"
    SYNTHETIC_ADAPTER = "SYNTHETIC_ADAPTER"


class SourceReliability(StrEnum):
    SYSTEM_OF_RECORD = "SYSTEM_OF_RECORD"
    VERIFIED_DOCUMENT = "VERIFIED_DOCUMENT"
    SYNTHETIC_TEST = "SYNTHETIC_TEST"
    OPERATOR_CONFIRMED = "OPERATOR_CONFIRMED"
    USER_REPORTED = "USER_REPORTED"


class StopReason(StrEnum):
    READY = "READY"
    NEED_MORE_EVIDENCE = "NEED_MORE_EVIDENCE"
    CONFIRMED_UNKNOWN = "CONFIRMED_UNKNOWN"
    UNSUPPORTED = "UNSUPPORTED"
    SECURITY_BLOCKED = "SECURITY_BLOCKED"


class TargetRole(StrEnum):
    MERCHANT_BUSINESS = "MERCHANT_BUSINESS"
    MERCHANT_TECH = "MERCHANT_TECH"
    INTERNAL_OPS = "INTERNAL_OPS"
    INTERNAL_RISK = "INTERNAL_RISK"
    INTERNAL_FINANCE = "INTERNAL_FINANCE"


class ReviewReason(StrEnum):
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    RISK_DECISION = "RISK_DECISION"
    SECURITY_SIGNAL = "SECURITY_SIGNAL"
    FINANCIAL_ACTION = "FINANCIAL_ACTION"
    POLICY_GAP = "POLICY_GAP"
    INSUFFICIENT_SOURCE_QUALITY = "INSUFFICIENT_SOURCE_QUALITY"


class ResponsibleTeam(StrEnum):
    BUSINESS = "BUSINESS"
    TECHNICAL_SUPPORT = "TECHNICAL_SUPPORT"
    RISK = "RISK"
    FINANCE = "FINANCE"
    CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT"
    PSP_SUPPORT = "PSP_SUPPORT"


class Priority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class DiagnosisStatus(StrEnum):
    CURRENT = "CURRENT"
    SUPERSEDED = "SUPERSEDED"


class WriteOutcome(StrEnum):
    CREATED = "CREATED"
    REPLAY = "REPLAY"


class AuditEventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    EVIDENCE_ADDED = "EVIDENCE_ADDED"
    DIAGNOSIS_SUPERSEDED = "DIAGNOSIS_SUPERSEDED"
    DIAGNOSIS_CREATED = "DIAGNOSIS_CREATED"
    ROUTING_PROPOSED = "ROUTING_PROPOSED"
    STATE_TRANSITIONED = "STATE_TRANSITIONED"


class AuditActorType(StrEnum):
    MERCHANT = "MERCHANT"
    INTERNAL_SYSTEM = "INTERNAL_SYSTEM"
    SYNTHETIC_ADAPTER = "SYNTHETIC_ADAPTER"


class EvidenceCode(StrEnum):
    CONTEXT_ENVIRONMENT = "context.environment"
    TRANSACTION_REFERENCE = "transaction.reference"
    TRANSACTION_OCCURRED_AT = "transaction.occurred_at"
    TRANSACTION_COUNTRY = "transaction.country"
    TRANSACTION_CURRENCY = "transaction.currency"
    PAYMENT_METHOD = "payment.method"
    INTEGRATION_TYPE = "integration.type"
    INTEGRATION_PLATFORM = "integration.platform"
    INTEGRATION_PLUGIN_VERSION = "integration.plugin_version"
    SYMPTOM_STATUS = "symptom.status"
    SYMPTOM_ERROR_CODE = "symptom.error_code"
    AUTHENTICATION_STATUS = "authentication.status"
    AUTHENTICATION_RESULT_CODE = "authentication.result_code"
    CALLBACK_DELIVERY_STATUS = "callback.delivery_status"
    RISK_DECISION_CODE = "risk.decision_code"
    CONFIGURATION_CHECK_RESULT = "configuration.check_result"
