/* A normalized upstream envelope is reviewed before it may create or update a case. */
(() => {
  "use strict";
  const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const names={FORMAL_DISPUTE:"正式争议",ALERT:"预警",INQUIRY:"查询",WITHDRAWAL:"撤回",CORRECTION:"更正",PROCESSED:"已处理",RECORDED:"已记录",QUARANTINED:"待核对",RECEIVED:"已接收",TRANSACTION_NOT_REGISTERED:"未找到已登记的对应交易",TRANSACTION_FACTS_MISMATCH:"上游事件与已登记交易不一致",CASE_ASSOCIATION_REQUIRES_VERIFICATION:"需要人工核对案件关联",AUTHORIZED_REOPEN_REQUIRED:"该案件需授权重开后才能继续",EVENT_TIMES_INVALID:"事件时间需要核对"};
  let state;
  const field=(name,title,type="text",optional=false,choices=null)=>`<label class="form-field"><span>${title}${optional?"（可选）":""}</span>${choices?`<select name="${name}"${optional?"":" required"}><option value="">请选择</option>${choices.map(value=>`<option value="${value}">${esc(names[value]||value)}</option>`).join("")}</select>`:`<input name="${name}" type="${type}"${optional?"":" required"}${type==="number"?' step="1" min="1" max="1000000000000"':' maxlength="500"'}>`}</label>`;
  function notice(text,error=false){if(!state)return;const node=state.dialog.querySelector('.intake-notice');node.textContent=text;node.hidden=!text;node.classList.toggle('error',error);}
  async function refresh(){if(!state?.host)return;try{const result=await state.api('/intake/events');state.events=Array.isArray(result)?result:result.events||[];state.host.innerHTML=`<details class="intake-events"><summary>上游事件与待核对事项 <span>${state.events.length} 条已授权记录</span></summary><p>正式争议经交易关联核验后才可立案。预警与查询保留事件记录；需要核对的事件会显示原因。</p>${state.events.slice().reverse().map(event=>`<article class="intake-event"><div><strong>${esc(names[event.event_type||event.envelope?.event_type]||event.event_type||"上游事件")}</strong><span class="badge ${event.status==='QUARANTINED'?'amber':'gray'}">${esc(names[event.status]||event.status)}</span></div><p>${esc(names[event.reason]||event.reason||event.source_event_id||event.id)}</p><small>${esc(event.channel||event.envelope?.channel||"")} · ${esc(event.id)}</small><div>${event.case_id?`<a class="button secondary small" href="/v2/operations/cases/${encodeURIComponent(event.case_id)}">打开关联案件</a>`:""}${event.status==='QUARANTINED'?`<button class="button secondary small" data-intake-retry="${esc(event.id)}">核对原事件并重试</button>`:""}</div><details><summary>查看原事件</summary><pre>${esc(JSON.stringify(event.envelope||event,null,2))}</pre></details></article>`).join("")||'<div class="empty-state compact">暂无可见上游事件。</div>'}</details>`;}catch(error){state.host.innerHTML=`<div class="notice error">上游事件暂时无法读取：${esc(error.message)}</div>`;}}
  function open(retryId){if(!state||state.busy)return;if(state.pending){state.dialog.showModal();notice("上一条事件的结果尚未确认，请使用原始信封重试。",true);return;}state.retry=retryId?state.events?.find(event=>event.id===retryId):null;
    const fields=state.dialog.querySelector('.intake-fields');state.dialog.querySelector('h2').textContent=state.retry?'核对原事件并重试':'接收标准化上游事件';
    fields.innerHTML=state.retry?`<pre>${esc(JSON.stringify(state.retry.envelope||state.retry,null,2))}</pre><label class="form-field"><span>本次核对或修复了什么</span><textarea name="retry_reason" minlength="3" maxlength="1000" required></textarea></label>`:`${field('event_type','上游事件类型','text',false,['FORMAL_DISPUTE','ALERT','INQUIRY','WITHDRAWAL','CORRECTION'])}${field('source_event_id','来源系统事件 ID')}${field('channel','来源渠道')}${field('merchant_id','对应商户 ID')}${field('transaction_id','原交易 ID')}${field('scheme','卡组织','text',false,['VISA','MASTERCARD'])}${field('amount_minor','交易金额（最小货币单位）','number')}${field('currency','币种')}${field('reason_code','原始原因码')}${field('received_at','实际收到事件的时间','datetime-local')}${field('occurred_at','上游事件发生时间','datetime-local')}<details class="intake-extra"><summary>已有案件关联、撤回或更正依据</summary>${field('upstream_case_id','来源系统案件编号','text',true)}${field('target_case_id','明确关联的 OceanPilot 案件','text',true)}${field('stage_number','事件所属轮次','number',true)}${field('outcome','上游明确的业务结果','text',true,['UNKNOWN','WON','LOST','PARTIAL','ACCEPTED_RESPONSIBILITY','WITHDRAWN','OTHER'])}<label class="form-field checkbox"><input type="checkbox" name="final">上游已明确确认终局</label>${field('corrects_event_id','本次更正的原事件 ID','text',true)}${field('basis_reference','核实与更正依据','text',true)}</details>`;
    state.dialog.querySelector('.intake-confirm').checked=false;notice('');state.dialog.showModal();
  }
  function mount({host,api,onCaseOpen}){
    if(state)return;const dialog=document.createElement('dialog');dialog.id='intakeEventDialog';dialog.className='intake-event-dialog';dialog.setAttribute('aria-labelledby','intakeEventTitle');dialog.innerHTML='<form class="intake-form"><div class="dialog-heading"><h2 id="intakeEventTitle">接收标准化上游事件</h2><button type="button" class="icon-button intake-close" aria-label="关闭">×</button></div><p class="section-note">逐项使用已收到的上游字段。服务器将核对交易归属和数据一致性；无法匹配的事件留待核对。</p><div class="intake-fields"></div><div class="intake-notice notice" role="status" hidden></div><label class="confirmation"><input class="intake-confirm" type="checkbox" required>我已核对原始事件、商户和交易关联，确认提交核验。</label><div class="dialog-footer"><button type="button" class="button secondary intake-close">取消</button><button type="submit" class="button primary intake-submit">确认并提交核验</button></div></form>';document.body.append(dialog);state={host,api,onCaseOpen,dialog,busy:false,pending:null,events:[]};
    dialog.querySelectorAll('.intake-close').forEach(button=>button.addEventListener('click',()=>{if(!state.busy)dialog.close();}));dialog.addEventListener('cancel',event=>{if(state.busy)event.preventDefault();});
    host?.addEventListener('click',event=>{const button=event.target.closest('[data-intake-retry]');if(button)open(button.dataset.intakeRetry);});
    dialog.querySelector('form').addEventListener('submit',async event=>{event.preventDefault();if(state.busy||!event.target.reportValidity())return;const form=event.target;
      let endpoint,body;try{if(state.pending){({endpoint,body}=state.pending);}else if(state.retry){endpoint=`/intake/events/${encodeURIComponent(state.retry.id)}/retry`;body={confirmed:true,reason:form.elements.retry_reason.value.trim()};}else{const values={};for(const[key,value]of new FormData(form).entries())if(String(value).trim())values[key]=String(value).trim();values.final=form.elements.final.checked;for(const key of['amount_minor','stage_number'])if(values[key])values[key]=Number(values[key]);for(const key of['occurred_at','received_at'])values[key]=new Date(values[key]).toISOString();if(values.occurred_at>values.received_at)throw new Error("事件发生时间不能晚于实际收到事件的时间。");endpoint='/intake/events';body={confirmed:true,event:values};}
        state.pending={endpoint,body};state.busy=true;form.querySelector('.intake-submit').disabled=true;notice('正在核对事件与交易关联…');const result=await api(endpoint,{method:'POST',body:JSON.stringify(body)});state.pending=null;const incoming=result.event||result;
        notice(`${names[incoming.status]||incoming.status||'事件已接收'}：${names[incoming.reason]||incoming.reason|| (result.case_id?'已关联案件。':'本事件已留存，未自动创建争议案件。')}`);await refresh();if(result.case_id){dialog.close();onCaseOpen?.(result.case_id);}else{form.querySelector('.intake-confirm').checked=false;}
      }catch(error){if(!error.uncertain)state.pending=null;notice(error.uncertain?'核验结果尚未确认。再次点击将使用原始事件信封核对，不会生成新的源事件。':error.message,true);}finally{state.busy=false;form.querySelector('.intake-submit').disabled=false;}
    });
    if(host)refresh();
  }
  globalThis.OceanV21Intake={mount,open,refresh};
})();
