"""Durable observation and conversation storage for the V2 workflow agent."""

from typing import Protocol


class DisputeAgentStore(Protocol):
    def get_run(self, case_id: str, revision: int) -> dict | None: ...

    def list_runs(self, case_id: str, limit: int = 100) -> list[dict]: ...

    def get_proposal(self, case_id: str, proposal_id: str) -> dict | None: ...

    def save_run(self, run: dict) -> dict: ...

    def list_conversations(self, case_id: str, limit: int = 100) -> list[dict]: ...

    def save_conversation(self, conversation: dict) -> dict: ...
