# -*- coding: utf-8 -*-
"""SYNTHETIC_DEMO 案例：为 OceanPilot 演示/测试/seed 组合多条规则合成的虚拟案件。
    使用虚构商户与虚构用户，Sandbox 编号，明确标注合成。"""

S = []

def _s(cid, title, scenario, industry, channel, txn_type, scheme, code, code_name, category,
       src, derived, fields_from_source, fields_invented, parties, fund, txn, dispute, evidence,
       outcome, ocean, process_flow, core=False, core_reason="", related=None, note=""):
    return dict(
        case_template_id=cid, evidence_level="SYNTHETIC_DEMO",
        source_ids=src, source_locations=["合成案例，无原文定位（见 derived_from_rule_ids）"],
        source_excerpt_short="N/A（合成案例，无原文摘录）",
        extraction_confidence="HIGH", requires_human_review=False,
        title_cn=title, scenario_one_line=scenario,
        industry=industry, channel=channel, transaction_type=txn_type,
        scheme=scheme, reason_code=code, reason_code_name=code_name,
        dispute_category=category, data_source_type="项目合成演示案例（虚构商户/虚构用户）",
        parties=parties, fund_flow=fund,
        transaction_facts=txn, dispute_facts=dispute, evidence_required=evidence,
        process_flow=process_flow, outcome=outcome, oceanpilot_mapping=ocean,
        synthetic_meta=dict(derived_from_rule_ids=derived, fields_from_source=fields_from_source,
                            fields_invented=fields_invented, note=note),
        duplicate_group_id=None, related_case_ids=related or [], core=core, core_reason=core_reason)

S.append(_s(
    "CB-CASE-060", "合成：证据充分的电商拒付抗辩案（13.1 类）",
    "虚构商户「云岚数码」(sandbox-mer-001) 被拒付 USD 299 耳机：物流轨迹完整、POD 签收人=持卡人、收货地址与账单地址一致。系统判定可抗辩并生成材料包。",
    "3C 电商", "线上", "实物商品", "Visa", "13.1", "Merchandise/Services Not Received", "Consumer Dispute",
    ["SRC-01", "SRC-03"], ["CB-CASE-026", "CB-CASE-041"],
    ["证据链要求（SRC-03 §5、SRC-01 P40-41）：Tracking+Delivery Address+Recipient+POD", "13.1 争议条件"],
    ["商户名、订单号、金额 USD 299、交易时间、物流单号、签收时间——全部为演示虚构"],
    dict(cardholder="Sandbox 用户 sandbox-user-001", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="云岚数码 sandbox-mer-001", psp="OceanPilot", platform="物流 sandbox-courier-001"),
    dict(who_paid_whom="持卡人向商户支付 USD 299", who_initiated="持卡人主张未收到", who_received_notice="商户（OceanPilot 案件中心）", who_bears_risk="商户（可抗辩）"),
    dict(transaction_id="sandbox-txn-060-0001", order_id="sandbox-ord-060-0001", transaction_time="2026-08-01T10:30:00Z", amount="USD 299", currency="USD",
         product_or_service="无线降噪耳机", payment_channel="电商 CNP", authentication_method="3DS 未强制（ECI 7）",
         delivery_or_service_status="已签收（POD 收件人=持卡人）", refund_status="未退款", customer_contact_status="无投诉前沟通"),
    dict(dispute_trigger="持卡人声称未收到商品", cardholder_claim="我没有收到耳机", issuer_notice="13.1 拒付通知（模拟报文）",
         reason_code="13.1", dispute_received_at="2026-08-25T02:00:00Z", response_deadline="2026-09-04T23:59:59Z（演示设定，Visa 天数需收单确认）",
         merchant_position="已妥投且签收人一致", initial_case_status="OPEN",
         should_accept_or_contest="CONTEST",
         recommendation_basis="证据链完整：Tracking→POD→收件人一致→地址匹配（依据 CB-CASE-026/041）"),
    [
        dict(evidence_type="TRACKING", evidence_name_cn="物流轨迹", required_or_optional="required", why_needed="证明运输", rule_reference="SRC-01 P40-41", expected_fields="运单号、轨迹", acceptable_format="PDF/系统记录", available_in_case="是", validation_method="物流系统核对", human_confirmation_required=False, missing_consequence="证据链断裂"),
        dict(evidence_type="POD", evidence_name_cn="签收证明", required_or_optional="required", why_needed="证明交付给本人", rule_reference="SRC-03 §5", expected_fields="签名、收件人、日期", acceptable_format="PDF", available_in_case="是", validation_method="收件人比对", human_confirmation_required=True, missing_consequence="无法抗辩"),
    ],
    dict(result="PENDING", result_basis="合成设定：已提交，等待上游回执", success_factors="证据链完整", failure_factors="N/A（演示正面路径）",
         preventable_or_not="是", merchant_improvement="维持签收留档", unresolved_questions="演示案件无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=True,
         required_product_modules=["首页待办", "案件列表", "案件详情", "证据上传与抽取", "准备度评估", "申诉草稿", "材料包", "人工审核", "上游提交"],
         recommended_demo_steps=["首页进入→查看证据链→准备度 95%→生成草稿→人工确认→提交→回执"],
         expected_agent_questions=["为什么可以抗辩？", "证据够了吗？"],
         expected_agent_actions=["评估证据完整度", "生成申诉草稿与材料包"],
         expected_system_blockers=["无（正面路径）"],
         acceptance_assertions=["准备度评分≥90", "草稿引用规则", "提交成功且幂等键唯一"]),
    dict(first_see="首页待办置顶（截止 9/4，高准备度）", auto="物流数据对接、证据抽取、准备度评分、草稿生成",
         ops="核对 POD 收件人", agent="解释证据链与建议抗辩", human="确认证据真实后一键确认", reviewer="审核提交",
         submit_condition="准备度达标+人工确认", upstream_result="提交成功（模拟回执 ack-060）", final_status="SUBMITTED"),
    core=True, core_reason="证据充分抗辩的正面主路径演示",
    related=["CB-CASE-026", "CB-CASE-041"], note="金额/时间/编号均为虚构，仅证据链规则来自资料"))

S.append(_s(
    "CB-CASE-061", "合成：证据严重缺失、系统阻止提交（10.4 欺诈）",
    "虚构商户被 10.4 欺诈拒付：无 3DS、无设备指纹、无历史交易（guest checkout）。系统准备度 12%，阻止提交并建议接受。",
    "跨境电商", "线上", "CNP 欺诈", "Visa", "10.4", "Other Fraud – Card-Absent Environment", "Fraud",
    ["SRC-01", "SRC-03"], ["CB-CASE-025", "CB-CASE-040"],
    ["CE3.0/Compelling Evidence 要求（SRC-03 §3、SRC-01 P26/P54-58）", "10.4 争议条件"],
    ["商户名、金额 EUR 459、guest checkout 场景"],
    dict(cardholder="Sandbox 用户 sandbox-user-002", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="环球优选 sandbox-mer-002", psp="OceanPilot", platform="独立站"),
    dict(who_paid_whom="持卡人被扣 EUR 459", who_initiated="持卡人否认交易", who_received_notice="商户", who_bears_risk="商户（无证据）"),
    dict(transaction_id="sandbox-txn-061-0001", order_id="sandbox-ord-061-0001", transaction_time="2026-08-10T18:00:00Z", amount="EUR 459", currency="EUR",
         product_or_service="智能手表", payment_channel="独立站 CNP", authentication_method="无 3DS（guest checkout）",
         delivery_or_service_status="已发货（无签收）", refund_status="未退款", customer_contact_status="无"),
    dict(dispute_trigger="持卡人否认交易", cardholder_claim="我没有买过", issuer_notice="10.4", reason_code="10.4",
         dispute_received_at="2026-08-28T01:00:00Z", response_deadline="2026-09-07T23:59:59Z（演示设定）",
         merchant_position="无法举证持卡人参与", initial_case_status="OPEN",
         should_accept_or_contest="ACCEPT",
         recommendation_basis="CE3.0 要素全缺（无认证/无设备/无历史交易），抗辩成功率依据规则极低"),
    [
        dict(evidence_type="AUTH", evidence_name_cn="3DS 认证记录", required_or_optional="required", why_needed="认证保护", rule_reference="SRC-01 P14/P26", expected_fields="ECI", acceptable_format="报文", available_in_case="否", validation_method="N/A", human_confirmation_required=False, missing_consequence="转向 CE"),
        dict(evidence_type="HISTORY", evidence_name_cn="同设备历史未争议交易", required_or_optional="required", why_needed="CE 核心", rule_reference="SRC-01 P26", expected_fields="设备/IP/时间", acceptable_format="记录", available_in_case="否", validation_method="N/A", human_confirmation_required=False, missing_consequence="无法抗辩"),
    ],
    dict(result="PENDING", result_basis="合成设定：等待商户选择接受", success_factors="N/A", failure_factors="证据全缺",
         preventable_or_not="是（可预防：强制 3DS）", merchant_improvement="强制 3DS 与注册登录", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=True, suitable_for_presentation_story=True,
         required_product_modules=["首页待办", "案件详情", "准备度评估", "Agent", "接受拒付流程", "飞书提醒"],
         recommended_demo_steps=["首页低准备度标记→Agent 解释为何无法抗辩→系统阻止提交→一键接受→通知"],
         expected_agent_questions=["为什么不能抗辩？", "缺什么？"],
         expected_agent_actions=["列出缺失证据并给出接受建议"],
         expected_system_blockers=["准备度<阈值：提交按钮禁用+原因展示"],
         acceptance_assertions=["提交被阻止", "建议=ACCEPT", "原因引用规则"]),
    dict(first_see="首页红色低准备度待办", auto="准备度 12%、阻断提交", ops="选择接受或补证",
         agent="解释证据缺失与 CE 条件", human="确认接受", reviewer="接受动作需审核权限",
         submit_condition="无（阻止抗辩提交）", upstream_result="接受回执（模拟）", final_status="ACCEPTED_BY_MERCHANT"),
    core=True, core_reason="证据不足阻止提交+建议接受的负面路径",
    related=["CB-CASE-025", "CB-CASE-040"], note="演示虚构；阻断阈值属 OceanPilot 产品设定"))

S.append(_s(
    "CB-CASE-062", "合成：更适合接受的拒付（4808 无授权）",
    "清算记录显示该笔交易从未获得授权批准（拒绝后无 Stand-in），结构化比对直接命中 4808。系统建议接受，不浪费时间收集证据。",
    "餐饮", "线下", "授权问题", "Mastercard", "4808", "Authorization-related Chargeback", "Authorization",
    ["SRC-02"], ["CB-CASE-049", "CB-CASE-007"],
    ["4808 触发条件与抗辩路径（SRC-02 P54-73）"],
    ["商户名、金额 USD 68、交易细节"],
    dict(cardholder="Sandbox 用户 sandbox-user-003", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="南巷小馆 sandbox-mer-003", psp="OceanPilot", platform="无"),
    dict(who_paid_whom="交易入账 USD 68", who_initiated="发卡行授权类拒付", who_received_notice="商户", who_bears_risk="商户（无授权）"),
    dict(transaction_id="sandbox-txn-062-0001", order_id="sandbox-ord-062-0001", transaction_time="2026-08-15T12:10:00Z", amount="USD 68", currency="USD",
         product_or_service="堂食消费", payment_channel="POS", authentication_method="无授权批准（拒绝后无 Stand-in）",
         delivery_or_service_status="已提供", refund_status="未退款", customer_contact_status="无"),
    dict(dispute_trigger="授权缺失", cardholder_claim="N/A（发卡行主张）", issuer_notice="4808", reason_code="4808",
         dispute_received_at="2026-08-30T03:00:00Z", response_deadline="2026-09-12T23:59:59Z（演示设定）",
         merchant_position="无授权记录", initial_case_status="OPEN",
         should_accept_or_contest="ACCEPT",
         recommendation_basis="授权数据结构化比对直接命中 4808，无可抗辩空间"),
    [
        dict(evidence_type="AUTH_LOG", evidence_name_cn="授权记录", required_or_optional="required", why_needed="2008 抗辩前提", rule_reference="SRC-02 P64-73", expected_fields="授权码", acceptable_format="报文", available_in_case="否", validation_method="规则引擎", human_confirmation_required=False, missing_consequence="建议接受"),
    ],
    dict(result="PENDING", result_basis="合成设定", success_factors="N/A", failure_factors="无授权",
         preventable_or_not="是", merchant_improvement="POS 操作规范（拒绝不成交）", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["案件详情", "规则引擎", "接受拒付流程"],
         recommended_demo_steps=["展示结构化比对结果→一键接受"],
         expected_agent_questions=["这笔能抗辩吗？"], expected_agent_actions=["说明授权缺失，建议接受"],
         expected_system_blockers=["规则命中直接建议接受"], acceptance_assertions=["建议=ACCEPT"]),
    dict(first_see="首页标记规则直判案件", auto="授权数据自动比对", ops="确认接受", agent="解释 4808 命中原因",
         human="确认接受", reviewer="审核接受动作", submit_condition="N/A",
         upstream_result="接受回执（模拟）", final_status="ACCEPTED_BY_MERCHANT"),
    core=True, core_reason="规则直判+接受路径演示",
    related=["CB-CASE-049"], note="演示虚构"))

S.append(_s(
    "CB-CASE-063", "合成：临近截止触发飞书提醒（13.1 未收到）",
    "证据已齐全但商户迟迟未处理，距离响应截止仅剩 3 天。系统向运营群发送飞书提醒卡片，运营当日完成提交。",
    "服装电商", "线上", "实物商品", "Visa", "13.1", "Merchandise/Services Not Received", "Consumer Dispute",
    ["SRC-01", "SRC-03"], ["CB-CASE-026", "CB-CASE-041"],
    ["13.1 证据链（SRC-03 §5）"],
    ["截止时间、飞书提醒阈值（产品设定）、商户与订单细节"],
    dict(cardholder="Sandbox 用户 sandbox-user-004", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="织语服饰 sandbox-mer-004", psp="OceanPilot", platform="物流 sandbox-courier-002"),
    dict(who_paid_whom="持卡人支付 USD 89", who_initiated="持卡人主张未收到", who_received_notice="商户", who_bears_risk="超期则视为放弃抗辩"),
    dict(transaction_id="sandbox-txn-063-0001", order_id="sandbox-ord-063-0001", transaction_time="2026-08-05T09:00:00Z", amount="USD 89", currency="USD",
         product_or_service="针织衫", payment_channel="电商", authentication_method="无", delivery_or_service_status="已签收",
         refund_status="未退款", customer_contact_status="无"),
    dict(dispute_trigger="未收到", cardholder_claim="没收到", issuer_notice="13.1", reason_code="13.1",
         dispute_received_at="2026-08-26T02:00:00Z", response_deadline="2026-09-05T23:59:59Z（演示设定）",
         merchant_position="证据已齐未提交", initial_case_status="OPEN",
         should_accept_or_contest="CONTEST", recommendation_basis="证据齐全，但必须赶在截止前提交"),
    [
        dict(evidence_type="POD", evidence_name_cn="签收证明", required_or_optional="required", why_needed="履约证明", rule_reference="SRC-03 §5", expected_fields="收件人", acceptable_format="PDF", available_in_case="是", validation_method="比对", human_confirmation_required=True, missing_consequence="无法抗辩"),
    ],
    dict(result="PENDING", result_basis="合成设定：已按时提交", success_factors="提醒及时", failure_factors="超期",
         preventable_or_not="是", merchant_improvement="及时响应案件", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=True, suitable_for_presentation_story=True,
         required_product_modules=["首页待办", "飞书提醒", "案件详情", "上游提交"],
         recommended_demo_steps=["演示飞书卡片到达→点击跳转案件→提交→回执"],
         expected_agent_questions=["还有多久截止？"], expected_agent_actions=["提示截止时间与剩余天数"],
         expected_system_blockers=["截止前 72 小时强制提醒"], acceptance_assertions=["飞书卡片含截止时间与链接"]),
    dict(first_see="首页置顶「临近截止」标签", auto="飞书提醒调度（T-72h）", ops="点击卡片处理案件",
         agent="说明截止风险", human="确认提交", reviewer="无需（已预审）",
         submit_condition="截止前提交", upstream_result="提交成功（模拟）", final_status="SUBMITTED"),
    core=True, core_reason="临近截止+飞书提醒演示",
    related=["CB-CASE-026"], note="提醒阈值与截止天数均为产品设定"))

S.append(_s(
    "CB-CASE-064", "合成：已过期案件（无法再提交）",
    "商户错过响应截止 6 天。系统锁定提交入口，状态置为 EXPIRED，并展示规则依据与商户改进建议。",
    "旅游", "预订", "取消退款", "Mastercard", "4853", "Cardholder Dispute", "Consumer Dispute",
    ["SRC-02"], ["CB-CASE-045", "CB-CASE-047"],
    ["4853 时限（SRC-02 P159 等）：120 天（大陆 90 天）"],
    ["截止时间、错过天数"],
    dict(cardholder="Sandbox 用户 sandbox-user-005", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="远方假期 sandbox-mer-005", psp="OceanPilot", platform="无"),
    dict(who_paid_whom="持卡人支付订金", who_initiated="持卡人主张退款未处理", who_received_notice="商户", who_bears_risk="商户（已失抗辩机会）"),
    dict(transaction_id="sandbox-txn-064-0001", order_id="sandbox-ord-064-0001", transaction_time="2026-06-20T10:00:00Z", amount="USD 420", currency="USD",
         product_or_service="度假套餐订金", payment_channel="卡支付", authentication_method="无",
         delivery_or_service_status="已取消", refund_status="未退款", customer_contact_status="有沟通"),
    dict(dispute_trigger="退款未处理", cardholder_claim="应退款", issuer_notice="4853", reason_code="4853",
         dispute_received_at="2026-07-30T02:00:00Z", response_deadline="2026-08-28T23:59:59Z（演示设定，已过 6 天）",
         merchant_position="未及时响应", initial_case_status="EXPIRED",
         should_accept_or_contest="ACCEPT", recommendation_basis="已过截止，系统锁定并默认接受"),
    [
        dict(evidence_type="REFUND_RECORD", evidence_name_cn="退款记录", required_or_optional="required", why_needed="本可抗辩", rule_reference="SRC-02 P273-276", expected_fields="退款", acceptable_format="记录", available_in_case="否", validation_method="N/A", human_confirmation_required=False, missing_consequence="已过期，不再收集"),
    ],
    dict(result="MERCHANT_LOST", result_basis="合成设定：超期未响应，视为放弃（演示，非卡组织裁决）",
         success_factors="N/A", failure_factors="错过截止",
         preventable_or_not="是", merchant_improvement="及时处理+开启飞书提醒", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=True, suitable_for_presentation_story=True,
         required_product_modules=["首页待办", "案件详情", "状态机", "Agent"],
         recommended_demo_steps=["打开过期案件→展示锁定状态与原因→Agent 复盘"],
         expected_agent_questions=["还能补交吗？"], expected_agent_actions=["说明已过截止，不能提交"],
         expected_system_blockers=["提交入口锁定"], acceptance_assertions=["状态=EXPIRED", "提交被禁"]),
    dict(first_see="首页「已过期」分组", auto="状态机自动置 EXPIRED", ops="复盘原因",
         agent="解释超期后果与改进建议", human="无需", reviewer="无需",
         submit_condition="禁止提交", upstream_result="N/A", final_status="EXPIRED"),
    core=True, core_reason="已过期状态机演示",
    related=["CB-CASE-045"], note="状态 EXPIRED 属 OceanPilot 状态机设计"))

S.append(_s(
    "CB-CASE-065", "合成：文件抽取需人工修正（证据 OCR 错误）",
    "上传的 POD 被 OCR 识别为收件人「张珊」，人工比对原件实为「张杉」且与持卡人一致。系统标记低置信度字段，运营修正后重新校验通过。",
    "家居电商", "线上", "实物商品", "Visa", "13.1", "Merchandise/Services Not Received", "Consumer Dispute",
    ["SRC-01", "SRC-03"], ["CB-CASE-026", "CB-CASE-041"],
    ["13.1 收件人比对要求（SRC-03 §5）"],
    ["OCR 错误、修正动作、人名（虚构）"],
    dict(cardholder="张杉 sandbox-user-006", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="素居生活 sandbox-mer-006", psp="OceanPilot", platform="物流 sandbox-courier-003"),
    dict(who_paid_whom="持卡人支付 USD 156", who_initiated="持卡人主张未收到", who_received_notice="商户", who_bears_risk="商户（可抗辩）"),
    dict(transaction_id="sandbox-txn-065-0001", order_id="sandbox-ord-065-0001", transaction_time="2026-08-08T14:00:00Z", amount="USD 156", currency="USD",
         product_or_service="台灯", payment_channel="电商", authentication_method="无", delivery_or_service_status="已签收",
         refund_status="未退款", customer_contact_status="无"),
    dict(dispute_trigger="未收到", cardholder_claim="没收到", issuer_notice="13.1", reason_code="13.1",
         dispute_received_at="2026-08-29T02:00:00Z", response_deadline="2026-09-08T23:59:59Z（演示设定）",
         merchant_position="已签收", initial_case_status="OPEN",
         should_accept_or_contest="CONTEST", recommendation_basis="收件人修正后与持卡人一致，证据链成立"),
    [
        dict(evidence_type="POD", evidence_name_cn="签收证明", required_or_optional="required", why_needed="收件人比对", rule_reference="SRC-03 §5", expected_fields="收件人姓名", acceptable_format="PDF", available_in_case="是（OCR 有误）", validation_method="人工比对原件", human_confirmation_required=True, missing_consequence="比对失败则无法抗辩"),
    ],
    dict(result="PENDING", result_basis="合成设定：修正后已提交", success_factors="人工修正及时", failure_factors="未复核",
         preventable_or_not="是", merchant_improvement="关键字段人工复核", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["证据上传与抽取", "案件详情", "人工审核"],
         recommended_demo_steps=["展示低置信字段高亮→人工修正→重新校验→提交"],
         expected_agent_questions=["张珊是谁？"], expected_agent_actions=["标记抽取置信度并请求人工核对"],
         expected_system_blockers=["低置信字段未修正禁止提交"], acceptance_assertions=["修正后校验通过"]),
    dict(first_see="证据页字段高亮提示低置信", auto="OCR 抽取+置信度评分", ops="比对原件修正字段",
         agent="提示需人工核对", human="修正收件人姓名", reviewer="复核修正",
         submit_condition="低置信字段已确认", upstream_result="提交成功（模拟）", final_status="SUBMITTED"),
    core=True, core_reason="文件抽取人工修正路径演示",
    related=["CB-CASE-026"], note="OCR 场景为产品设定"))

S.append(_s(
    "CB-CASE-066", "合成：Agent 生成操作提案、用户确认后执行（4853 课程）",
    "数字课程拒付：Agent 检索到 17 次登录记录，生成「提交抗辩」操作提案，附材料包与规则引用；用户确认后提案被执行，全程留痕。",
    "在线教育", "线上", "数字服务", "Mastercard", "4853", "Cardholder Dispute", "Consumer Dispute",
    ["SRC-02", "SRC-03"], ["CB-CASE-031", "CB-CASE-046"],
    ["4853 消费证据链（SRC-03 §12）"],
    ["登录次数、提案流程（产品设定）、虚构商户"],
    dict(cardholder="Sandbox 用户 sandbox-user-007", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="启明学堂 sandbox-mer-007", psp="OceanPilot", platform="课程平台"),
    dict(who_paid_whom="持卡人支付 USD 499", who_initiated="持卡人主张课程不可访问", who_received_notice="商户", who_bears_risk="商户（可抗辩）"),
    dict(transaction_id="sandbox-txn-066-0001", order_id="sandbox-ord-066-0001", transaction_time="2026-08-02T11:00:00Z", amount="USD 499", currency="USD",
         product_or_service="在线课程", payment_channel="电商", authentication_method="账号", delivery_or_service_status="登录 17 次",
         refund_status="未退款", customer_contact_status="无"),
    dict(dispute_trigger="服务不可用", cardholder_claim="课程打不开", issuer_notice="4853", reason_code="4853",
         dispute_received_at="2026-08-27T02:00:00Z", response_deadline="2026-09-06T23:59:59Z（演示设定）",
         merchant_position="已被使用", initial_case_status="OPEN",
         should_accept_or_contest="CONTEST", recommendation_basis="消费日志构成证据链"),
    [
        dict(evidence_type="USAGE_LOG", evidence_name_cn="登录/访问记录", required_or_optional="required", why_needed="证明使用", rule_reference="SRC-03 §12", expected_fields="账号、登录次数、时间", acceptable_format="日志", available_in_case="是", validation_method="日志核对", human_confirmation_required=False, missing_consequence="无法抗辩"),
    ],
    dict(result="PENDING", result_basis="合成设定：提案执行后已提交", success_factors="证据充分", failure_factors="N/A",
         preventable_or_not="是", merchant_improvement="记录消费行为", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=True,
         required_product_modules=["Agent", "操作提案", "申诉草稿", "材料包", "审计"],
         recommended_demo_steps=["Agent 生成提案→展示规则引用与材料包→用户确认→提案执行→审计留痕"],
         expected_agent_questions=["帮我准备抗辩"], expected_agent_actions=["生成提案（不直接提交）"],
         expected_system_blockers=["未确认前提案不执行"], acceptance_assertions=["提案含规则引用", "确认后执行", "审计日志完整"]),
    dict(first_see="Agent 面板展示提案预览", auto="检索证据+生成提案", ops="审查提案",
         agent="解释提案依据", human="确认提案", reviewer="无需（提案含证据）",
         submit_condition="用户确认提案", upstream_result="提交成功（模拟）", final_status="SUBMITTED"),
    core=True, core_reason="Agent 提案+用户确认的产品交互演示",
    related=["CB-CASE-031"], note="提案机制为产品设定"))

S.append(_s(
    "CB-CASE-067", "合成：提案因 case revision 过期被拒绝",
    "Agent 生成提案后，另一运营同时更新了案件（版本号 +1）。用户点击确认时系统检测 revision 不匹配，拒绝执行并要求基于最新版本重新生成。",
    "3C 电商", "线上", "实物商品", "Mastercard", "4853", "Cardholder Dispute", "Consumer Dispute",
    ["SRC-02"], ["CB-CASE-045"],
    ["4853 抗辩证据要求（SRC-02 P157-177）"],
    ["并发更新、revision 机制（产品设定）"],
    dict(cardholder="Sandbox 用户 sandbox-user-008", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="极光数码 sandbox-mer-008", psp="OceanPilot", platform="无"),
    dict(who_paid_whom="持卡人支付 USD 88", who_initiated="持卡人主张货不对板", who_received_notice="商户", who_bears_risk="商户"),
    dict(transaction_id="sandbox-txn-067-0001", order_id="sandbox-ord-067-0001", transaction_time="2026-08-11T15:00:00Z", amount="USD 88", currency="USD",
         product_or_service="键盘", payment_channel="电商", authentication_method="无", delivery_or_service_status="已收货",
         refund_status="未退款", customer_contact_status="有沟通"),
    dict(dispute_trigger="货不对板", cardholder_claim="描述不符", issuer_notice="4853", reason_code="4853",
         dispute_received_at="2026-08-31T02:00:00Z", response_deadline="2026-09-10T23:59:59Z（演示设定）",
         merchant_position="已按约交付", initial_case_status="OPEN",
         should_accept_or_contest="CONTEST", recommendation_basis="基于最新版本证据重新提案"),
    [
        dict(evidence_type="MERCHANT_NARRATIVE", evidence_name_cn="按约交付说明", required_or_optional="required", why_needed="2700 抗辩", rule_reference="SRC-02 P160-170", expected_fields="说明", acceptable_format="文档", available_in_case="是", validation_method="人工", human_confirmation_required=True, missing_consequence="抗辩不成立"),
    ],
    dict(result="PENDING", result_basis="合成设定：重新生成提案后提交", success_factors="版本检测生效", failure_factors="N/A",
         preventable_or_not="是", merchant_improvement="协作时留意版本提示", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["Agent", "操作提案", "案件详情", "并发控制"],
         recommended_demo_steps=["演示并发更新→确认被拒→基于新版本重新生成→提交"],
         expected_agent_questions=["为什么执行失败？"], expected_agent_actions=["解释 revision 过期并重新生成提案"],
         expected_system_blockers=["revision 不匹配拒绝执行"], acceptance_assertions=["过期提案被拒绝", "新提案成功"]),
    dict(first_see="确认弹窗报「案件已更新」", auto="revision 检测", ops="重新处理",
         agent="基于最新版本重新生成", human="再次确认", reviewer="审核",
         submit_condition="提案版本=当前版本", upstream_result="提交成功（模拟）", final_status="SUBMITTED"),
    core=True, core_reason="乐观锁/case revision 并发演示",
    related=["CB-CASE-066"], note="revision 机制为产品设定"))

S.append(_s(
    "CB-CASE-068", "合成：上游提交超时后幂等重试成功",
    "提交抗辩时上游接口超时。系统以幂等键重试，未产生重复提交，最终收到成功回执；审计记录显示一次业务提交+两次网络重试。",
    "服装电商", "线上", "实物商品", "Visa", "13.1", "Merchandise/Services Not Received", "Consumer Dispute",
    ["SRC-01", "SRC-03"], ["CB-CASE-026", "CB-CASE-041"],
    ["13.1 证据链（SRC-03 §5）"],
    ["超时与重试（产品设定）"],
    dict(cardholder="Sandbox 用户 sandbox-user-009", issuer="发卡行（模拟）", acquirer="上游收单（模拟）", merchant="栖木服饰 sandbox-mer-009", psp="OceanPilot", platform="无"),
    dict(who_paid_whom="持卡人支付 USD 132", who_initiated="持卡人主张未收到", who_received_notice="商户", who_bears_risk="商户（可抗辩）"),
    dict(transaction_id="sandbox-txn-068-0001", order_id="sandbox-ord-068-0001", transaction_time="2026-08-12T16:00:00Z", amount="USD 132", currency="USD",
         product_or_service="风衣", payment_channel="电商", authentication_method="无", delivery_or_service_status="已签收",
         refund_status="未退款", customer_contact_status="无"),
    dict(dispute_trigger="未收到", cardholder_claim="没收到", issuer_notice="13.1", reason_code="13.1",
         dispute_received_at="2026-08-30T02:00:00Z", response_deadline="2026-09-09T23:59:59Z（演示设定）",
         merchant_position="已签收", initial_case_status="OPEN",
         should_accept_or_contest="CONTEST", recommendation_basis="证据链成立，重试机制保证提交成功"),
    [
        dict(evidence_type="POD", evidence_name_cn="签收证明", required_or_optional="required", why_needed="履约证明", rule_reference="SRC-03 §5", expected_fields="收件人", acceptable_format="PDF", available_in_case="是", validation_method="比对", human_confirmation_required=True, missing_consequence="无法抗辩"),
    ],
    dict(result="PENDING", result_basis="合成设定：重试后收到回执", success_factors="幂等键", failure_factors="N/A",
         preventable_or_not="是", merchant_improvement="N/A", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=True,
         required_product_modules=["上游提交", "幂等与重试", "审计"],
         recommended_demo_steps=["点击提交→模拟超时→自动重试→成功回执→展示审计"],
         expected_agent_questions=["提交失败了吗？"], expected_agent_actions=["说明幂等重试结果"],
         expected_system_blockers=["无（重试是内部机制）"], acceptance_assertions=["无重复提交", "回执唯一"]),
    dict(first_see="提交按钮转圈后提示重试中", auto="幂等重试（3 次退避）", ops="无需干预",
         agent="汇报重试结果", human="无需", reviewer="无需",
         submit_condition="幂等键一致", upstream_result="回执 ack-068（模拟）", final_status="SUBMITTED"),
    core=True, core_reason="上游超时幂等重试的可靠性演示",
    related=["CB-CASE-060"], note="超时与重试为产品设定"))

S.append(_s(
    "CB-CASE-069", "合成：跨租户访问必须被阻断（安全测试）",
    "租户 A 的运营人员携带租户 B 的案件 ID 访问，系统鉴权层返回 403；越权尝试被写入安全审计，触发告警。",
    "通用（安全）", "通用", "安全测试", "N/A（产品安全）", "N/A", "Cross-tenant access", "Security",
    ["SRC-01", "SRC-02"], ["CB-CASE-060"],
    ["无（纯产品安全设计，与卡组织规则无关）"],
    ["租户模型、403 行为、告警（产品设定）"],
    dict(cardholder="N/A", issuer="N/A", acquirer="N/A", merchant="租户 A=云岚数码 sandbox-mer-001；租户 B=环球优选 sandbox-mer-002", psp="OceanPilot", platform="N/A"),
    dict(who_paid_whom="N/A", who_initiated="租户 A 成员试图访问租户 B 案件", who_received_notice="N/A", who_bears_risk="越权访问风险"),
    dict(transaction_id="N/A", order_id="N/A", transaction_time="N/A", amount="N/A", currency="N/A",
         product_or_service="N/A", payment_channel="N/A", authentication_method="租户鉴权", delivery_or_service_status="N/A",
         refund_status="N/A", customer_contact_status="N/A"),
    dict(dispute_trigger="N/A", cardholder_claim="N/A", issuer_notice="N/A", reason_code="N/A",
         dispute_received_at="N/A", response_deadline="N/A", merchant_position="N/A", initial_case_status="N/A",
         should_accept_or_contest="INSUFFICIENT_INFORMATION", recommendation_basis="N/A（安全测试）"),
    [],
    dict(result="NOT_STATED", result_basis="安全测试用例，无业务结局", success_factors="鉴权生效", failure_factors="越权泄露",
         preventable_or_not="NOT_APPLICABLE", merchant_improvement="N/A", unresolved_questions="N/A"),
    dict(suitable_for_demo=True, suitable_for_seed_data=False, suitable_for_rule_test=False, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=True, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["权限与鉴权", "审计", "告警"],
         recommended_demo_steps=["跨租户 URL 访问→403→审计告警"],
         expected_agent_questions=["为什么打不开？"], expected_agent_actions=["拒绝并提供最小信息"],
         expected_system_blockers=["租户边界强制"], acceptance_assertions=["403 返回", "审计留痕"]),
    dict(first_see="403 页面", auto="鉴权拦截+审计写入", ops="无需", agent="不泄露其他租户信息",
         human="无需", reviewer="安全审计复查",
         submit_condition="N/A", upstream_result="N/A", final_status="BLOCKED"),
    core=True, core_reason="跨租户安全测试用例",
    related=[], note="纯产品安全设计"))

S.append(_s(
    "CB-CASE-070", "合成：规则版本变化但历史快照不变",
    "案件处理期间 Mastercard 旧码 4855 被标记将淘汰、并入 4853。案件仍按受理时的规则版本 2026-05 展示证据要求；新案件使用 2026-06 版本。",
    "电商", "线上", "商品未收到", "Mastercard", "4853/4855", "Cardholder Dispute（版本切换）", "Consumer Dispute",
    ["SRC-02", "SRC-03"], ["CB-CASE-046"],
    ["淘汰码并入规则（SRC-02 P182 等、SRC-03 §11）"],
    ["规则版本号、快照行为（产品设定）"],
    dict(cardholder="Sandbox 用户 sandbox-user-010", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="森屿杂货 sandbox-mer-010", psp="OceanPilot", platform="无"),
    dict(who_paid_whom="持卡人支付 USD 45", who_initiated="持卡人主张未收到", who_received_notice="商户", who_bears_risk="商户"),
    dict(transaction_id="sandbox-txn-070-0001", order_id="sandbox-ord-070-0001", transaction_time="2026-08-13T10:00:00Z", amount="USD 45", currency="USD",
         product_or_service="家居用品", payment_channel="电商", authentication_method="无", delivery_or_service_status="已发货",
         refund_status="未退款", customer_contact_status="无"),
    dict(dispute_trigger="未收到", cardholder_claim="没收到", issuer_notice="4855（旧码，将并入 4853）", reason_code="4855→4853",
         dispute_received_at="2026-08-29T02:00:00Z", response_deadline="2026-09-08T23:59:59Z（演示设定）",
         merchant_position="已发货", initial_case_status="OPEN",
         should_accept_or_contest="CONDITIONAL", recommendation_basis="按受理版本规则展示证据要求，不受后续版本影响"),
    [
        dict(evidence_type="DELIVERY", evidence_name_cn="交付证明", required_or_optional="required", why_needed="履约", rule_reference="SRC-02 P182-184", expected_fields="交付记录", acceptable_format="文档", available_in_case="是", validation_method="核对", human_confirmation_required=True, missing_consequence="抗辩无据"),
    ],
    dict(result="PENDING", result_basis="合成设定", success_factors="快照稳定", failure_factors="版本混淆",
         preventable_or_not="是", merchant_improvement="N/A", unresolved_questions="真实版本切换机制"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["规则版本管理", "案件快照", "审计"],
         recommended_demo_steps=["展示历史案件规则快照 vs 新案件新版本"],
         expected_agent_questions=["规则怎么变了？"], expected_agent_actions=["说明版本与快照机制"],
         expected_system_blockers=["历史案件禁止套用新规则"], acceptance_assertions=["快照版本号正确"]),
    dict(first_see="案件详情显示规则版本 2026-05", auto="快照绑定受理版本", ops="无需",
         agent="解释版本差异", human="无需", reviewer="无需",
         submit_condition="按快照规则校验", upstream_result="提交成功（模拟）", final_status="SUBMITTED"),
    core=True, core_reason="规则版本与历史快照演示",
    related=["CB-CASE-046"], note="版本切换为产品设定"))

S.append(_s(
    "CB-CASE-071", "合成：路演开场故事——友好欺诈（账单描述不清）",
    "路演开场：一家独立设计店铺收到「持卡人不认识这笔交易」的拒付。Agent 调出订单照片与商品描述后，运营发现是友好欺诈，用历史交易+设备证据抗辩成功。",
    "原创设计零售", "线上", "CNP 欺诈/友好欺诈", "Visa", "10.4", "Other Fraud – Card-Absent Environment", "Fraud",
    ["SRC-01", "SRC-03"], ["CB-CASE-025", "CB-CASE-034", "CB-CASE-040"],
    ["CE3.0 证据要求（SRC-03 §3、SRC-01 P26）", "账单描述预防（SRC-03 §20）"],
    ["全部商户/订单/金额为虚构"],
    dict(cardholder="Sandbox 用户 sandbox-user-011", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="拾光设计 sandbox-mer-011", psp="OceanPilot", platform="独立站"),
    dict(who_paid_whom="持卡人支付 USD 310", who_initiated="持卡人称不认识交易", who_received_notice="商户", who_bears_risk="商户（可抗辩）"),
    dict(transaction_id="sandbox-txn-071-0001", order_id="sandbox-ord-071-0001", transaction_time="2026-08-06T20:00:00Z", amount="USD 310", currency="USD",
         product_or_service="手工皮包", payment_channel="独立站 CNP", authentication_method="3DS（ECI 5）",
         delivery_or_service_status="已签收", refund_status="未退款", customer_contact_status="无"),
    dict(dispute_trigger="持卡人不认识交易", cardholder_claim="这笔交易不是我做的", issuer_notice="10.4", reason_code="10.4",
         dispute_received_at="2026-08-26T02:00:00Z", response_deadline="2026-09-05T23:59:59Z（演示设定）",
         merchant_position="3DS 认证+历史交易可证", initial_case_status="OPEN",
         should_accept_or_contest="CONTEST", recommendation_basis="ECI 5 认证+同设备历史交易+签收，构成抗辩链"),
    [
        dict(evidence_type="AUTH", evidence_name_cn="3DS 认证（ECI 5）", required_or_optional="required", why_needed="认证保护", rule_reference="SRC-01 P14", expected_fields="ECI", acceptable_format="报文", available_in_case="是", validation_method="规则引擎", human_confirmation_required=False, missing_consequence="保护缺失"),
        dict(evidence_type="HISTORY", evidence_name_cn="同设备历史交易", required_or_optional="optional", why_needed="佐证本人交易", rule_reference="SRC-01 P26", expected_fields="设备/IP", acceptable_format="记录", available_in_case="是", validation_method="匹配", human_confirmation_required=False, missing_consequence="佐证减弱"),
        dict(evidence_type="POD", evidence_name_cn="签收证明", required_or_optional="optional", why_needed="佐证收货", rule_reference="SRC-01 P54", expected_fields="收件人", acceptable_format="PDF", available_in_case="是", validation_method="比对", human_confirmation_required=True, missing_consequence="佐证减弱"),
    ],
    dict(result="MERCHANT_WON", result_basis="合成设定：演示抗辩成功（非真实裁决，仅路演叙事）",
         success_factors="认证+历史+签收", failure_factors="N/A",
         preventable_or_not="是", merchant_improvement="账单描述清晰化+3DS", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=True, suitable_for_presentation_story=True,
         required_product_modules=["首页待办", "案件详情", "Agent", "准备度评估", "上游提交"],
         recommended_demo_steps=["开场叙事→展示证据链→提交→成功回执（路演）"],
         expected_agent_questions=["这笔交易是谁的？"], expected_agent_actions=["组织证据链并讲解"],
         expected_system_blockers=["无"], acceptance_assertions=["证据链讲解正确"]),
    dict(first_see="路演首页进入该案件", auto="证据聚合与评分", ops="按脚本演示", agent="讲解友好欺诈",
         human="确认提交", reviewer="无需", submit_condition="证据齐全",
         upstream_result="模拟胜诉回执（路演设定）", final_status="MERCHANT_WON"),
    core=True, core_reason="路演开场故事（通俗+真实规则支撑）",
    related=["CB-CASE-034"], note="胜诉为路演设定，非真实裁决"))

S.append(_s(
    "CB-CASE-072", "合成：退款未到账（seed 数据）",
    "商户 8 月 20 日发起退款 USD 120，持卡人 8 月 30 日仍称未收到。系统检索到退款 ARN 与结算状态，生成 2011/13.6 抗辩。",
    "美妆电商", "线上", "退款未到账", "Visa", "13.6", "Credit Not Processed", "Consumer Dispute",
    ["SRC-01", "SRC-03"], ["CB-CASE-029", "CB-CASE-047"],
    ["13.6 退款关联要求（SRC-03 §8）"],
    ["订单/退款明细为虚构"],
    dict(cardholder="Sandbox 用户 sandbox-user-012", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="澄心美妆 sandbox-mer-012", psp="OceanPilot", platform="无"),
    dict(who_paid_whom="持卡人支付后商户退款", who_initiated="持卡人主张退款未到", who_received_notice="商户", who_bears_risk="商户（可证已退）"),
    dict(transaction_id="sandbox-txn-072-0001", order_id="sandbox-ord-072-0001", transaction_time="2026-08-18T09:00:00Z", amount="USD 120", currency="USD",
         product_or_service="护肤品套装", payment_channel="电商", authentication_method="无", delivery_or_service_status="已退货",
         refund_status="已发起退款（ARN sandbox-arn-072）", customer_contact_status="有客服记录"),
    dict(dispute_trigger="退款未到账", cardholder_claim="退款没收到", issuer_notice="13.6", reason_code="13.6",
         dispute_received_at="2026-08-30T02:00:00Z", response_deadline="2026-09-09T23:59:59Z（演示设定）",
         merchant_position="退款已结算", initial_case_status="OPEN",
         should_accept_or_contest="CONTEST", recommendation_basis="ARN+退款交易记录是核心证据"),
    [
        dict(evidence_type="REFUND_TX", evidence_name_cn="退款 ARN/日期/金额/结算状态", required_or_optional="required", why_needed="证明退款", rule_reference="SRC-03 §8", expected_fields="ARN、金额、结算状态", acceptable_format="记录", available_in_case="是", validation_method="关联校验", human_confirmation_required=False, missing_consequence="建议接受"),
    ],
    dict(result="PENDING", result_basis="合成设定", success_factors="ARN 可查", failure_factors="仅聊天记录",
         preventable_or_not="是", merchant_improvement="退款即时留 ARN", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["退款匹配", "案件详情", "Agent"],
         recommended_demo_steps=["展示原交易↔退款关联→提交"],
         expected_agent_questions=["退款真的发了吗？"], expected_agent_actions=["检索 ARN 并核对结算状态"],
         expected_system_blockers=["无 ARN 建议接受"], acceptance_assertions=["匹配正确"]),
    dict(first_see="案件详情展示退款关联", auto="退款匹配", ops="核对结算状态", agent="解释 ARN 证据价值",
         human="确认", reviewer="审核", submit_condition="退款记录完整",
         upstream_result="提交成功（模拟）", final_status="SUBMITTED"),
    core=False, related=["CB-CASE-029"], note="seed 可脱敏复用"))

S.append(_s(
    "CB-CASE-073", "合成：重复扣款（seed 数据）",
    "同一订单被扣两笔 USD 66。系统比对订单号/授权/清算发现两笔指向同一订单，判定重复；商户确认后走退款补救并接受拒付。",
    "运动电商", "线上", "重复扣款", "Mastercard", "4834", "Point-of-Interaction Error", "Processing Error",
    ["SRC-02", "SRC-03"], ["CB-CASE-030", "CB-CASE-043", "CB-CASE-050"],
    ["重复判定多字段比对（SRC-03 §9）"],
    ["订单/金额为虚构"],
    dict(cardholder="Sandbox 用户 sandbox-user-013", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="锐动体育 sandbox-mer-013", psp="OceanPilot", platform="无"),
    dict(who_paid_whom="持卡人被扣两笔 USD 66", who_initiated="持卡人主张重复", who_received_notice="商户", who_bears_risk="重复部分商户"),
    dict(transaction_id="sandbox-txn-073-0001 / -0002", order_id="sandbox-ord-073-0001（两笔同单）", transaction_time="2026-08-14T10:01:00Z / 10:02:00Z", amount="USD 66 × 2", currency="USD",
         product_or_service="跑鞋", payment_channel="电商", authentication_method="无", delivery_or_service_status="已发货（一笔）",
         refund_status="未退款", customer_contact_status="无"),
    dict(dispute_trigger="重复扣款", cardholder_claim="被扣两次", issuer_notice="4834", reason_code="4834",
         dispute_received_at="2026-08-31T02:00:00Z", response_deadline="2026-09-10T23:59:59Z（演示设定）",
         merchant_position="确认为系统重复扣款", initial_case_status="OPEN",
         should_accept_or_contest="ACCEPT", recommendation_basis="两笔指向同一订单，判定重复，应退款并接受"),
    [
        dict(evidence_type="ORDER_MATCH", evidence_name_cn="订单/授权/清算比对", required_or_optional="required", why_needed="重复判定", rule_reference="SRC-03 §9", expected_fields="订单号、授权、清算", acceptable_format="记录", available_in_case="是", validation_method="规则引擎", human_confirmation_required=True, missing_consequence="无法判定"),
    ],
    dict(result="ACCEPTED_BY_MERCHANT", result_basis="合成设定：接受并退款补救", success_factors="判定清晰", failure_factors="N/A",
         preventable_or_not="是", merchant_improvement="扣款幂等控制", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["重复判定", "退款补救", "案件详情"],
         recommended_demo_steps=["展示多字段比对→接受→退款补救"],
         expected_agent_questions=["是重复吗？"], expected_agent_actions=["多字段比对并建议退款"],
         expected_system_blockers=["重复判定未确认禁止提交"], acceptance_assertions=["判定正确"]),
    dict(first_see="首页标记疑似重复", auto="多字段比对", ops="确认重复并退款", agent="解释判定依据",
         human="确认接受", reviewer="审核接受", submit_condition="N/A（接受）",
         upstream_result="接受回执（模拟）", final_status="ACCEPTED_BY_MERCHANT"),
    core=False, related=["CB-CASE-030"], note="seed 可脱敏复用"))

S.append(_s(
    "CB-CASE-074", "合成：货不对板抗辩（seed 数据，4853）",
    "持卡人称收到的台灯为旧款。商户提供 SKU、发货序列号与商品页快照证明一致，生成 2700 抗辩。",
    "家居电商", "线上", "货不对板", "Mastercard", "4853", "Cardholder Dispute", "Consumer Dispute",
    ["SRC-02", "SRC-03"], ["CB-CASE-028", "CB-CASE-045"],
    ["13.3/4853 一致性证明（SRC-03 §7、SRC-02 P157-177）"],
    ["订单/商品细节为虚构"],
    dict(cardholder="Sandbox 用户 sandbox-user-014", issuer="发卡行（模拟）", acquirer="收单机构（模拟）", merchant="简居家居 sandbox-mer-014", psp="OceanPilot", platform="无"),
    dict(who_paid_whom="持卡人支付 USD 98", who_initiated="持卡人主张货不对板", who_received_notice="商户", who_bears_risk="商户（可抗辩）"),
    dict(transaction_id="sandbox-txn-074-0001", order_id="sandbox-ord-074-0001", transaction_time="2026-08-16T13:00:00Z", amount="USD 98", currency="USD",
         product_or_service="台灯（新款）", payment_channel="电商", authentication_method="无", delivery_or_service_status="已收货",
         refund_status="未退款", customer_contact_status="有沟通"),
    dict(dispute_trigger="货不对板", cardholder_claim="收到旧款", issuer_notice="4853", reason_code="4853",
         dispute_received_at="2026-08-30T02:00:00Z", response_deadline="2026-09-09T23:59:59Z（演示设定）",
         merchant_position="SKU 与序列号一致", initial_case_status="OPEN",
         should_accept_or_contest="CONTEST", recommendation_basis="SKU+序列号+页面快照构成一致性证明"),
    [
        dict(evidence_type="PRODUCT_DESC", evidence_name_cn="SKU/商品页快照", required_or_optional="required", why_needed="一致性证明", rule_reference="SRC-03 §7", expected_fields="SKU、描述", acceptable_format="截图", available_in_case="是", validation_method="比对", human_confirmation_required=True, missing_consequence="抗辩无据"),
        dict(evidence_type="DELIVERY_RECORD", evidence_name_cn="发货序列号记录", required_or_optional="required", why_needed="证明所发商品", rule_reference="SRC-03 §7", expected_fields="序列号", acceptable_format="记录", available_in_case="是", validation_method="序列号核对", human_confirmation_required=True, missing_consequence="抗辩无据"),
    ],
    dict(result="PENDING", result_basis="合成设定", success_factors="序列号一致", failure_factors="记录缺失",
         preventable_or_not="是", merchant_improvement="发货留序列号", unresolved_questions="演示无真实裁决"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=False, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["案件详情", "证据上传"],
         recommended_demo_steps=["展示描述 vs 交付对比"],
         expected_agent_questions=["货对版吗？"], expected_agent_actions=["对比 SKU 与序列号"],
         expected_system_blockers=["记录缺失阻止提交"], acceptance_assertions=["对比正确"]),
    dict(first_see="案件详情对比视图", auto="SKU 与序列号比对", ops="上传快照", agent="解释一致性证明",
         human="确认", reviewer="审核", submit_condition="证据齐全",
         upstream_result="提交成功（模拟）", final_status="SUBMITTED"),
    core=False, related=["CB-CASE-028"], note="seed 可脱敏复用"))
