# -*- coding: utf-8 -*-
"""RULE_DERIVED 案例：由原因码/规则还原的典型场景（非原文完整故事，标注为规则还原）。"""

def _base(level="RULE_DERIVED"):
    return dict(evidence_level=level, requires_human_review=False, extraction_confidence="HIGH",
                data_source_type="规则还原场景", transaction_id="NOT_STATED", order_id="NOT_STATED")

R = []

def _r(cid, title, scenario, industry, channel, txn_type, scheme, code, code_name, category,
       src, loc, excerpt, parties, fund, txn, dispute, evidence, outcome, ocean, core=False, core_reason="", related=None, conf="HIGH"):
    d = dict(
        case_template_id=cid, evidence_level="RULE_DERIVED",
        source_ids=src, source_locations=loc, source_excerpt_short=excerpt,
        extraction_confidence=conf, requires_human_review=False,
        title_cn=title, scenario_one_line=scenario,
        industry=industry, channel=channel, transaction_type=txn_type,
        scheme=scheme, reason_code=code, reason_code_name=code_name,
        dispute_category=category, data_source_type="规则还原场景（原文仅给原因码+规则，无完整故事）",
        parties=parties, fund_flow=fund,
        transaction_facts=txn, dispute_facts=dispute, evidence_required=evidence,
        process_flow=dict(first_see="案件进入后按原因码匹配规则", auto="规则引擎装载对应条件与证据清单", ops="按清单收集证据",
                          agent="解释原因码与证据要求", human="确认关键事实", reviewer="审核后放行",
                          submit_condition="证据满足对应原因码要求", upstream_result="NOT_STATED", final_status="PENDING"),
        outcome=outcome, oceanpilot_mapping=ocean, duplicate_group_id=None,
        related_case_ids=related or [], core=core, core_reason=core_reason)
    return d

R.append(_r(
    "CB-CASE-040", "Visa 10.4 CNP 欺诈：典型证据链场景（规则还原）",
    "持卡人否认一笔无卡交易。商户可提交认证记录+2 笔 120–365 天内清算的同设备历史交易（CE），或 16 项 Compelling Evidence 之一。",
    "电商", "线上", "CNP 欺诈", "Visa", "10.4", "Other Fraud – Card-Absent Environment", "Fraud",
    ["SRC-01", "SRC-03"], ["SRC-01 P26/P54-58", "SRC-03 §3"],
    "The cardholder is claiming that they did not authorize or participate in a transaction conducted in a card-absent environment.",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="电商商户", psp="NOT_STATED", platform="电商网站"),
    dict(who_paid_whom="持卡人被扣款", who_initiated="持卡人向发卡行否认交易", who_received_notice="商户", who_bears_risk="默认商户承担，除非 CE 成立"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="CNP", authentication_method="可选 3DS",
         delivery_or_service_status="NOT_STATED", refund_status="NOT_STATED", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="持卡人不认可交易", cardholder_claim="我没有做这笔交易", issuer_notice="10.4", reason_code="10.4",
         dispute_received_at="NOT_STATED", response_deadline="NOT_STATED（Visa 未给天数）", merchant_position="NOT_STATED",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="CE3.0/Compelling Evidence 满足则可抗辩，否则建议接受"),
    [
        dict(evidence_type="AUTH", evidence_name_cn="3DS/认证记录", required_or_optional="optional", why_needed="认证成功可获保护", rule_reference="SRC-01 P14/P26", expected_fields="ECI、认证时间", acceptable_format="报文", available_in_case="视案件而定", validation_method="规则引擎读取", human_confirmation_required=False, missing_consequence="转向 CE 证据"),
        dict(evidence_type="HISTORY", evidence_name_cn="2 笔同设备/同IP历史未争议交易", required_or_optional="required", why_needed="CE 抗辩核心", rule_reference="SRC-01 P26", expected_fields="设备ID/指纹、IP、时间（120–365 天窗口）", acceptable_format="交易记录", available_in_case="视案件而定", validation_method="匹配校验", human_confirmation_required=False, missing_consequence="CE 不成立"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原，无结局", success_factors="CE 要素齐全", failure_factors="无历史交易",
         preventable_or_not="是", merchant_improvement="采集设备指纹与历史交易", unresolved_questions="Visa 响应天数需收单机构确认"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=True,
         required_product_modules=["案件详情", "证据上传", "准备度评估", "Agent"],
         recommended_demo_steps=["展示 CE 匹配→准备度评分→提交/接受"],
         expected_agent_questions=["这个欺诈案能抗辩吗？", "缺什么证据？"],
         expected_agent_actions=["执行 CE3.0 匹配并列出缺失证据"],
         expected_system_blockers=["证据不足时阻止提交并建议接受"],
         acceptance_assertions=["CE 判定正确", "缺失项列表正确"]),
    core=True, core_reason="欺诈类规则还原的基准场景",
    related=["CB-CASE-025", "CB-CASE-061"]))

R.append(_r(
    "CB-CASE-041", "Visa 13.1 商品/服务未收到：典型场景（规则还原）",
    "持卡人声称未收到商品。商户需证明该争议交易对应的商品确实履约给了该消费者（签收、自提、航班起飞、NFT 钱包哈希等）。",
    "电商/物流", "线上", "实物商品/服务", "Visa", "13.1", "Merchandise/Services Not Received", "Consumer Dispute",
    ["SRC-01", "SRC-03"], ["SRC-01 P40-41", "SRC-03 §5"],
    "The cardholder claims that merchandise or services that they ordered were not received by the expected date.",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="商户", psp="NOT_STATED", platform="物流商"),
    dict(who_paid_whom="持卡人付款", who_initiated="持卡人主张未收到", who_received_notice="商户", who_bears_risk="无法证明履约则商户"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="NOT_STATED", authentication_method="NOT_STATED",
         delivery_or_service_status="争议中", refund_status="NOT_STATED", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="未收到商品/服务", cardholder_claim="没收到", issuer_notice="13.1", reason_code="13.1",
         dispute_received_at="NOT_STATED", response_deadline="NOT_STATED", merchant_position="NOT_STATED",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="证据链（Tracking→Delivery→Recipient→POD）完整则抗辩"),
    [
        dict(evidence_type="TRACKING", evidence_name_cn="物流轨迹/航班起飞证明", required_or_optional="required", why_needed="证明运输", rule_reference="SRC-01 P40-41", expected_fields="运单/航段", acceptable_format="系统记录", available_in_case="视案件而定", validation_method="系统核对", human_confirmation_required=False, missing_consequence="无法证明发货"),
        dict(evidence_type="POD", evidence_name_cn="签收证明/自提记录/服务使用日志", required_or_optional="required", why_needed="证明交付给对应消费者", rule_reference="SRC-01 P40-41", expected_fields="收件人、签名、日期", acceptable_format="POD/日志", available_in_case="视案件而定", validation_method="收件人比对", human_confirmation_required=True, missing_consequence="证据链断裂"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="POD 收件人一致", failure_factors="仅订单状态",
         preventable_or_not="是", merchant_improvement="签收留档", unresolved_questions="代收效力"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["案件详情", "证据上传", "Agent"],
         recommended_demo_steps=["证据链视图→上传 POD→提交"],
         expected_agent_questions=["需要哪些证据？"], expected_agent_actions=["列出证据链要求"],
         expected_system_blockers=["POD 缺失阻止提交"], acceptance_assertions=["证据链判定正确"]),
    core=False, related=["CB-CASE-026", "CB-CASE-060"]))

R.append(_r(
    "CB-CASE-042", "Visa 11.3 无授权/逾期清算：典型场景（规则还原）",
    "交易未获授权、超额、或未在时限内清算（2024-04-13 起并入 11.3）。大量依据是结构化交易数据，适合自动判责。",
    "通用", "线上/线下", "授权问题", "Visa", "11.3", "No Authorization / Late Presentment", "Authorization",
    ["SRC-01", "SRC-03"], ["SRC-01 P31", "SRC-03 §10"],
    "A transaction was processed without obtaining the required authorization, or the transaction was not processed within the required transaction processing time limit.",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="商户", psp="NOT_STATED", platform="无"),
    dict(who_paid_whom="交易入账", who_initiated="发卡行拒付", who_received_notice="收单行/商户", who_bears_risk="授权缺失由商户承担"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="NOT_STATED", authentication_method="授权", delivery_or_service_status="NOT_STATED",
         refund_status="NOT_STATED", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="授权缺失/逾期清算", cardholder_claim="N/A（发卡行主张）", issuer_notice="11.3", reason_code="11.3",
         dispute_received_at="NOT_STATED", response_deadline="NOT_STATED", merchant_position="授权存在且按时清算",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="自动比对授权响应/授权码/金额/清算日期决定接受或抗辩"),
    [
        dict(evidence_type="AUTH_LOG", evidence_name_cn="授权响应/授权码/金额/清算日期", required_or_optional="required", why_needed="证明授权有效且按时清算", rule_reference="SRC-03 §10；SRC-01 P31", expected_fields="授权码、金额、交易日、清算日", acceptable_format="报文", available_in_case="视案件而定", validation_method="规则引擎自动比对", human_confirmation_required=False, missing_consequence="建议接受"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="结构化数据齐全", failure_factors="数据缺失",
         preventable_or_not="是", merchant_improvement="确保授权与清算合规", unresolved_questions="11.3 生效日切换逻辑"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=False, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["规则引擎", "案件详情"],
         recommended_demo_steps=["展示自动判责结果"],
         expected_agent_questions=["这笔授权有问题吗？"], expected_agent_actions=["比对授权与清算数据"],
         expected_system_blockers=["数据缺失时转人工"], acceptance_assertions=["判责结果正确"]),
    core=False, related=[]))

R.append(_r(
    "CB-CASE-043", "Visa 12.6 重复处理/已其他方式付款：典型场景（规则还原）",
    "同一凭证同交易日同金额处理多次（12.6.1），或持卡人已用其他方式付款（12.6.2）。需多字段比对而非仅凭金额。",
    "通用", "线上/线下", "处理错误", "Visa", "12.6.1/12.6.2", "Duplicate Processing / Paid by Other Means", "Processing Error",
    ["SRC-01", "SRC-03"], ["SRC-01 P37-38", "SRC-03 §9"],
    "The cardholder claims that a single transaction was processed more than once using the same Payment Credential on the same Transaction date, and for the same Transaction amount.",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="商户", psp="NOT_STATED", platform="无"),
    dict(who_paid_whom="持卡人付款（可能两次）", who_initiated="持卡人主张重复/已另行付款", who_received_notice="商户", who_bears_risk="重复部分商户"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="NOT_STATED", authentication_method="NOT_STATED",
         delivery_or_service_status="NOT_STATED", refund_status="NOT_STATED", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="重复扣款", cardholder_claim="被扣两次/已其他方式付款", issuer_notice="12.6", reason_code="12.6",
         dispute_received_at="NOT_STATED", response_deadline="NOT_STATED", merchant_position="两笔独立",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="比对 Order ID/SKU/Authorization/Capture/Invoice 判定"),
    [
        dict(evidence_type="ORDER_MATCH", evidence_name_cn="订单/授权/清算多字段比对", required_or_optional="required", why_needed="判定是否重复", rule_reference="SRC-03 §9", expected_fields="Order ID、授权、清算", acceptable_format="记录", available_in_case="视案件而定", validation_method="规则引擎", human_confirmation_required=True, missing_consequence="无法判定"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="订单号区分", failure_factors="仅凭金额",
         preventable_or_not="是", merchant_improvement="扣款挂订单号", unresolved_questions="同订单两笔认定"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=False, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["重复判定", "案件详情"],
         recommended_demo_steps=["展示多字段比对"],
         expected_agent_questions=["算重复吗？"], expected_agent_actions=["多字段比对"],
         expected_system_blockers=["金额相同但字段不全→转人工"], acceptance_assertions=["判定正确"]),
    core=False, related=["CB-CASE-030", "CB-CASE-073"]))

R.append(_r(
    "CB-CASE-044", "Visa 13.7 已取消商品/服务：典型场景（规则还原）",
    "持卡人取消商品/服务但账单未退款（含分时度假 14 天、担保预订 No-show 费）。商户需披露政策+证明取消不符合约定。",
    "旅游/服务", "预订", "取消退款", "Visa", "13.7", "Cancelled Merchandise/Services", "Consumer Dispute",
    ["SRC-01"], ["SRC-01 P49-50"],
    "A Timeshare cancellation was not processed within 14 days of the contract or receipt date.",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="商户", psp="NOT_STATED", platform="无"),
    dict(who_paid_whom="持卡人预付", who_initiated="持卡人主张取消未退款", who_received_notice="商户", who_bears_risk="未按政策退款商户"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="预订/商品", payment_channel="卡支付", authentication_method="NOT_STATED",
         delivery_or_service_status="已取消", refund_status="未退款", customer_contact_status="已取消"),
    dict(dispute_trigger="取消未退款", cardholder_claim="已取消", issuer_notice="13.7", reason_code="13.7",
         dispute_received_at="NOT_STATED", response_deadline="NOT_STATED", merchant_position="取消超期/不合规",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="政策披露+取消时间判定"),
    [
        dict(evidence_type="POLICY", evidence_name_cn="取消/退款政策披露证明", required_or_optional="required", why_needed="证明政策已告知", rule_reference="SRC-01 P17/P49-50", expected_fields="披露记录", acceptable_format="截图/小票", available_in_case="视案件而定", validation_method="人工核对", human_confirmation_required=True, missing_consequence="须退款"),
        dict(evidence_type="TIMESTAMP", evidence_name_cn="取消时间/未按政策取消证明", required_or_optional="required", why_needed="证明取消不符合约定", rule_reference="SRC-01 P49-50", expected_fields="取消时间", acceptable_format="记录", available_in_case="视案件而定", validation_method="时间比对", human_confirmation_required=True, missing_consequence="抗辩无据"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="披露+超期证据", failure_factors="政策未披露",
         preventable_or_not="是", merchant_improvement="政策显式披露", unresolved_questions="各州立法差异"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=False, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["案件详情", "时间线视图"],
         recommended_demo_steps=["展示取消时间线"],
         expected_agent_questions=["取消政策生效吗？"], expected_agent_actions=["比对披露与取消时间"],
         expected_system_blockers=["政策未披露→建议退款"], acceptance_assertions=["判定正确"]),
    core=False, related=["CB-CASE-023", "CB-CASE-033"]))

R.append(_r(
    "CB-CASE-045", "Mastercard 4853 货不对板/瑕疵：典型场景（规则还原）",
    "持卡人称商品与描述不符或损坏。商户可抗辩：已修/已换/按约交付（2700）、单据篡改（2001）、退货欺诈（2004）、已退款（2011）、拒付无效。",
    "电商/零售", "线上", "实物商品", "Mastercard", "4853", "Cardholder Dispute", "Consumer Dispute",
    ["SRC-02", "SRC-03"], ["SRC-02 P157-177/P953-967", "SRC-03 §28"],
    "The cardholder engaged in the transaction; the merchandise or services were not as described or were defective.",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="商户", psp="NOT_STATED", platform="无"),
    dict(who_paid_whom="持卡人付款", who_initiated="持卡人主张货不对板", who_received_notice="商户", who_bears_risk="举证责任在商户"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="NOT_STATED", authentication_method="NOT_STATED",
         delivery_or_service_status="已收货但争议", refund_status="NOT_STATED", customer_contact_status="已联系商户"),
    dict(dispute_trigger="货不对板", cardholder_claim="与描述不符/有缺陷", issuer_notice="4853", reason_code="4853",
         dispute_received_at="NOT_STATED", response_deadline="120 天（SP 30/45 天地区而异）", merchant_position="已按约交付",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="按 2700/2001/2004/2011/无效清单选择抗辩路径"),
    [
        dict(evidence_type="MERCHANT_NARRATIVE", evidence_name_cn="已修/已换/按约交付说明", required_or_optional="required", why_needed="2700 抗辩", rule_reference="SRC-02 P160-170", expected_fields="修复/更换记录、签收", acceptable_format="文档", available_in_case="视案件而定", validation_method="人工核对", human_confirmation_required=True, missing_consequence="转向其他抗辩"),
        dict(evidence_type="INSPECTION", evidence_name_cn="专家/检验意见", required_or_optional="optional", why_needed="强化质量/真实性证明", rule_reference="SRC-02 P158-159", expected_fields="意见", acceptable_format="报告", available_in_case="视案件而定", validation_method="人工审查", human_confirmation_required=True, missing_consequence="主观争议难反驳"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="修复记录清晰", failure_factors="无记录",
         preventable_or_not="是", merchant_improvement="质检留档", unresolved_questions="主观瑕疵判定尺度"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["案件详情", "证据上传", "Agent"],
         recommended_demo_steps=["选择抗辩路径→上传证据→提交"],
         expected_agent_questions=["货不对板怎么抗辩？"], expected_agent_actions=["列出抗辩路径与证据"],
         expected_system_blockers=["证据不足阻止提交"], acceptance_assertions=["路径与证据匹配"]),
    core=False, related=["CB-CASE-028"]))

R.append(_r(
    "CB-CASE-046", "Mastercard 4853 商品/服务未提供：典型场景（规则还原）",
    "持卡人称未收到商品（含空箱、延迟交付、商户停业）。时限：120 天（大陆 90 天）；延迟交付无约定日期须等 30 天后提。",
    "电商/服务", "线上", "实物/服务", "Mastercard", "4853", "Cardholder Dispute（Goods or Services Not Provided）", "Consumer Dispute",
    ["SRC-02"], ["SRC-02 P177-184/P967-983"],
    "This chargeback applies when the cardholder receives an empty box or a box containing worthless items, such as a brick or a stack of paper.",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="商户", psp="NOT_STATED", platform="物流"),
    dict(who_paid_whom="持卡人付款", who_initiated="持卡人主张未收到", who_received_notice="商户", who_bears_risk="商户举证履约"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="NOT_STATED", authentication_method="NOT_STATED",
         delivery_or_service_status="未收到", refund_status="NOT_STATED", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="未收到", cardholder_claim="没收到商品/服务", issuer_notice="4853", reason_code="4853",
         dispute_received_at="NOT_STATED", response_deadline="120 天（大陆 90 天；停业礼品卡 540 天）", merchant_position="已提供",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="交付照片/签收/QR 使用记录/机票已用等证据则抗辩"),
    [
        dict(evidence_type="DELIVERY", evidence_name_cn="交付证明（签收/QR/PIN 使用/航班已发生）", required_or_optional="required", why_needed="证明已提供", rule_reference="SRC-02 P183/P972", expected_fields="交付记录", acceptable_format="文档/日志", available_in_case="视案件而定", validation_method="核对", human_confirmation_required=True, missing_consequence="抗辩无据"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="交付证明完整", failure_factors="无记录",
         preventable_or_not="是", merchant_improvement="交付留档", unresolved_questions="代收效力"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=False, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["案件详情", "证据上传"],
         recommended_demo_steps=["上传交付证明→提交"],
         expected_agent_questions=["要什么证据？"], expected_agent_actions=["列出交付证明要求"],
         expected_system_blockers=["无证明阻止提交"], acceptance_assertions=["判定正确"]),
    core=False, related=["CB-CASE-004", "CB-CASE-031"]))

R.append(_r(
    "CB-CASE-047", "Mastercard 4853 退款未处理：典型场景（规则还原）",
    "持卡人应得退款未处理（含 VAT 退税）。商户抗辩：退款本不欠（2700）/已退款（2011）/退货欺诈（2004）。退款须在 SP 中记录。",
    "通用", "通用", "退款", "Mastercard", "4853", "Cardholder Dispute（Refund Not Processed）", "Consumer Dispute",
    ["SRC-02"], ["SRC-02 P273-276/P1036-1051"],
    "The cardholder claims that a refund or credit was expected but not processed.",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="商户", psp="NOT_STATED", platform="无"),
    dict(who_paid_whom="应退款未退", who_initiated="持卡人主张退款未处理", who_received_notice="商户", who_bears_risk="未退款商户"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="NOT_STATED", authentication_method="NOT_STATED",
         delivery_or_service_status="NOT_STATED", refund_status="未处理", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="退款未处理", cardholder_claim="应退未退", issuer_notice="4853", reason_code="4853",
         dispute_received_at="NOT_STATED", response_deadline="15–120 天（VAT 120 天）", merchant_position="退款不欠/已退",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="已退款则 2011 并在 SP 记录；不欠则 2700"),
    [
        dict(evidence_type="REFUND_RECORD", evidence_name_cn="退款记录", required_or_optional="required", why_needed="证明已退或不该退", rule_reference="SRC-02 P273-276", expected_fields="退款日期、金额、ARD", acceptable_format="记录", available_in_case="视案件而定", validation_method="核对", human_confirmation_required=False, missing_consequence="建议退款"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="退款记录可查", failure_factors="无记录",
         preventable_or_not="是", merchant_improvement="退款即时同步", unresolved_questions="部分退款处理"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=False, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["退款匹配", "案件详情"],
         recommended_demo_steps=["退款匹配→SP 记录→提交"],
         expected_agent_questions=["退款查得到吗？"], expected_agent_actions=["检索退款记录"],
         expected_system_blockers=["无记录建议接受"], acceptance_assertions=["匹配正确"]),
    core=False, related=["CB-CASE-029", "CB-CASE-072"]))

R.append(_r(
    "CB-CASE-048", "Mastercard 4837 无持卡人授权：典型场景（规则还原）",
    "持卡人声称未授权交易。商户抗辩路径多：addendum 责任、AVS 匹配、认证（ECI 211/212/217/242）、Compelling Evidence、No-show、退款、14 项无效拒付。",
    "通用", "线上/线下", "欺诈/未授权", "Mastercard", "4837", "No Cardholder Authorization", "Fraud",
    ["SRC-02", "SRC-03"], ["SRC-02 P489-563", "SRC-03 §28"],
    "The cardholder claims that he or she did not authorize the transaction.",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="商户", psp="NOT_STATED", platform="无"),
    dict(who_paid_whom="交易扣款", who_initiated="持卡人否认授权", who_received_notice="商户", who_bears_risk="商户默认"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="NOT_STATED", authentication_method="可选 3DS/AVS",
         delivery_or_service_status="NOT_STATED", refund_status="NOT_STATED", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="未授权", cardholder_claim="我没授权", issuer_notice="4837", reason_code="4837",
         dispute_received_at="NOT_STATED", response_deadline="120 天（大陆 5–90 天）", merchant_position="持卡人参与了交易",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="认证/CE/AVS/历史交易满足则可抗辩；guest checkout 无 CE"),
    [
        dict(evidence_type="AUTH", evidence_name_cn="3DS 认证（ECI 211/212/217/242）", required_or_optional="optional", why_needed="认证抗辩", rule_reference="SRC-02 P503", expected_fields="ECI", acceptable_format="报文", available_in_case="视案件而定", validation_method="规则引擎", human_confirmation_required=False, missing_consequence="转向 CE"),
        dict(evidence_type="COMP_EVID", evidence_name_cn="Compelling Evidence（注册/历史交易等）", required_or_optional="optional", why_needed="证明持卡人参与", rule_reference="SRC-02 P505-509", expected_fields="注册记录、设备、历史交易", acceptable_format="记录", available_in_case="视案件而定", validation_method="匹配", human_confirmation_required=False, missing_consequence="无 CE 则建议接受"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="认证/CE 齐全", failure_factors="guest checkout",
         preventable_or_not="是", merchant_improvement="强制注册+3DS", unresolved_questions="First-Party Trust 扩展节奏"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=True, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=True,
         required_product_modules=["案件详情", "CE 匹配", "Agent"],
         recommended_demo_steps=["展示认证/CE 匹配结果"],
         expected_agent_questions=["没授权能抗辩吗？"], expected_agent_actions=["检查认证与 CE"],
         expected_system_blockers=["无 CE 建议接受"], acceptance_assertions=["匹配正确"]),
    core=False, related=["CB-CASE-025", "CB-CASE-040", "CB-CASE-061"]))

R.append(_r(
    "CB-CASE-049", "Mastercard 4808 授权相关拒付：典型场景（规则还原）",
    "发卡行主张授权类问题：未获授权、离线芯片超 7 天清算、退款超 5 天、账户状态化、拒绝后 Stand-in 批准、CAT 3 违规、Transit FRR/FRIL。",
    "通用", "通用", "授权", "Mastercard", "4808", "Authorization-related Chargeback", "Authorization",
    ["SRC-02"], ["SRC-02 P54-150/P880-947"],
    "Authorization-related chargeback message reason code 4808/08.",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="商户", psp="NOT_STATED", platform="无"),
    dict(who_paid_whom="交易入账", who_initiated="发卡行拒付", who_received_notice="收单行", who_bears_risk="授权违规方"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="NOT_STATED", authentication_method="授权", delivery_or_service_status="NOT_STATED",
         refund_status="NOT_STATED", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="授权类拒付", cardholder_claim="N/A", issuer_notice="4808", reason_code="4808",
         dispute_received_at="NOT_STATED", response_deadline="90 天（SP 30/45 天）", merchant_position="授权正确取得",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="2008 授权已取得/2713 一次授权多笔清算/2011 已退款"),
    [
        dict(evidence_type="AUTH_LOG", evidence_name_cn="授权记录", required_or_optional="required", why_needed="2008/2713 抗辩", rule_reference="SRC-02 P64-73/P889-890", expected_fields="授权码、日期、金额", acceptable_format="报文", available_in_case="视案件而定", validation_method="规则引擎", human_confirmation_required=False, missing_consequence="建议接受"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="授权记录完整", failure_factors="记录缺失",
         preventable_or_not="是", merchant_improvement="授权合规", unresolved_questions="SP 时限 30/45 差异"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=False, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["规则引擎", "案件详情"],
         recommended_demo_steps=["展示授权比对"],
         expected_agent_questions=["授权有问题吗？"], expected_agent_actions=["比对授权记录"],
         expected_system_blockers=["无记录建议接受"], acceptance_assertions=["判定正确"]),
    core=False, related=["CB-CASE-007", "CB-CASE-008"]))

R.append(_r(
    "CB-CASE-050", "Mastercard 4834 POI 错误（重复扣款等）：典型场景（规则还原）",
    "POI 错误九类：重复扣款、金额错、cash back 未给、ATM 未出钞、loss/theft/damage、币种错、退款纠错汇损、不当附加费、不合理金额。",
    "通用/ATM/零售", "通用", "处理错误", "Mastercard", "4834", "Point-of-Interaction Error", "Processing Error",
    ["SRC-02"], ["SRC-02 P685-776/P1324-1407"],
    "Point-of-Interaction Error (Message Reason Codes 4834/34).",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="商户/ATM", psp="NOT_STATED", platform="无"),
    dict(who_paid_whom="交易扣款", who_initiated="持卡人主张处理错误", who_received_notice="商户", who_bears_risk="处理错误方"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="NOT_STATED", authentication_method="NOT_STATED",
         delivery_or_service_status="NOT_STATED", refund_status="NOT_STATED", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="POI 错误", cardholder_claim="扣款有误", issuer_notice="4834", reason_code="4834",
         dispute_received_at="NOT_STATED", response_deadline="90/120 天（子类而异）", merchant_position="处理正确",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="2700 对应纠正证据；差额类只退差额"),
    [
        dict(evidence_type="TX_RECORD", evidence_name_cn="终端/交易记录（按子类）", required_or_optional="required", why_needed="证明处理正确", rule_reference="SRC-02 P685-776", expected_fields="按子类：ATM 日志/收据/终端数据", acceptable_format="记录", available_in_case="视案件而定", validation_method="规则引擎/人工", human_confirmation_required=True, missing_consequence="建议接受"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="记录完整", failure_factors="记录缺失",
         preventable_or_not="是", merchant_improvement="终端与清算数据质量", unresolved_questions="4834/4831 过渡"),
    dict(suitable_for_demo=True, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=False, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["规则引擎", "案件详情"],
         recommended_demo_steps=["展示子类判定"],
         expected_agent_questions=["属于哪类 POI 错误？"], expected_agent_actions=["子类判定并给证据清单"],
         expected_system_blockers=["证据缺失建议接受"], acceptance_assertions=["子类判定正确"]),
    core=False, related=["CB-CASE-014", "CB-CASE-017", "CB-CASE-073"]))

R.append(_r(
    "CB-CASE-051", "Mastercard 4870/4871 芯片责任转移：典型场景（规则还原）",
    "伪卡/遗失被盗卡在非芯片终端交易，责任向未处理芯片的一方转移。商户抗辩：DE 55 已提供、非芯片责任交易、FNS>35、未上报欺诈库等。",
    "线下零售", "线下", "欺诈", "Mastercard", "4870/4871", "Chip Liability Shift (Counterfeit / Lost-Stolen-NRI)", "Fraud",
    ["SRC-02"], ["SRC-02 P578-636/P1241-1288"],
    "Chip Liability Shift (Message Reason Codes 4870/70 and 4871).",
    dict(cardholder="持卡人", issuer="发卡行", acquirer="收单行", merchant="线下商户", psp="NOT_STATED", platform="无"),
    dict(who_paid_whom="交易扣款", who_initiated="持卡人否认交易", who_received_notice="商户", who_bears_risk="按芯片责任规则转移"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="芯片卡/磁条", authentication_method="EMV/PIN",
         delivery_or_service_status="NOT_STATED", refund_status="NOT_STATED", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="芯片责任转移拒付", cardholder_claim="未授权", issuer_notice="4870/4871", reason_code="4870/4871",
         dispute_received_at="NOT_STATED", response_deadline="120 天", merchant_position="芯片数据已提交",
         initial_case_status="OPEN", should_accept_or_contest="CONDITIONAL",
         recommendation_basis="DE 55 已提供或非责任转移交易则抗辩"),
    [
        dict(evidence_type="EMV_DATA", evidence_name_cn="DE 55/芯片数据/终端能力", required_or_optional="required", why_needed="责任判定", rule_reference="SRC-02 P588-589", expected_fields="DE 55、fallback 标识、CVM", acceptable_format="报文", available_in_case="视案件而定", validation_method="规则引擎", human_confirmation_required=False, missing_consequence="责任转移"),
    ],
    dict(result="NOT_STATED", result_basis="规则还原", success_factors="DE 55 完整", failure_factors="fallback 未标识",
         preventable_or_not="是", merchant_improvement="终端升级支持芯片", unresolved_questions="4871 章节 4870 代码残留"),
    dict(suitable_for_demo=False, suitable_for_seed_data=True, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=False, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["规则引擎"],
         recommended_demo_steps=[],
         expected_agent_questions=["责任算谁的？"], expected_agent_actions=["按 DE 55 判定责任"],
         expected_system_blockers=[], acceptance_assertions=["责任判定正确"]),
    core=False, related=[]))

R.append(_r(
    "CB-CASE-052", "Amex C08/C02：未收到商品与退款未处理（规则映射还原）",
    "Amex 无官方原文时仅据 SRC-03 映射：C08=未收到商品、C02=退款未处理；证据要求按 Visa/MC 同类场景类比，需 Amex 原文确认。",
    "通用", "通用", "商品/退款", "American Express", "C08 / C02", "Goods/Services Not Received / Credit Not Processed", "Consumer Dispute",
    ["SRC-03"], ["SRC-03 §28"],
    "编号2 服务未提供或未收到商品→C08；编号8 未收到退款→C02（ODPM 映射表）。",
    dict(cardholder="持卡人", issuer="Amex", acquirer="收单方", merchant="商户", psp="NOT_STATED", platform="无"),
    dict(who_paid_whom="持卡人付款", who_initiated="持卡人主张未收到/未退款", who_received_notice="商户", who_bears_risk="商户"),
    dict(transaction_id="NOT_STATED", order_id="NOT_STATED", transaction_time="NOT_STATED", amount="NOT_STATED", currency="NOT_STATED",
         product_or_service="NOT_STATED", payment_channel="NOT_STATED", authentication_method="NOT_STATED",
         delivery_or_service_status="NOT_STATED", refund_status="NOT_STATED", customer_contact_status="NOT_STATED"),
    dict(dispute_trigger="未收到/退款未处理", cardholder_claim="NOT_STATED", issuer_notice="C08/C02", reason_code="C08/C02",
         dispute_received_at="NOT_STATED", response_deadline="NOT_STATED（原文缺失）", merchant_position="NOT_STATED",
         initial_case_status="OPEN", should_accept_or_contest="INSUFFICIENT_INFORMATION",
         recommendation_basis="Amex 原文缺失，按同类场景逻辑暂列证据清单，需业务确认"),
    [
        dict(evidence_type="DELIVERY", evidence_name_cn="交付/退款证明（类比）", required_or_optional="required", why_needed="证明履约或退款", rule_reference="SRC-03 §28（映射，非 Amex 原文）", expected_fields="交付/退款记录", acceptable_format="记录", available_in_case="视案件而定", validation_method="人工", human_confirmation_required=True, missing_consequence="建议接受"),
    ],
    dict(result="NOT_STATED", result_basis="无 Amex 原文", success_factors="NOT_STATED", failure_factors="NOT_STATED",
         preventable_or_not="NOT_STATED", merchant_improvement="NOT_STATED", unresolved_questions="Amex C 系列官方证据与时限（GAP-005）"),
    dict(suitable_for_demo=False, suitable_for_seed_data=False, suitable_for_rule_test=True, suitable_for_agent_test=True,
         suitable_for_ui_test=False, suitable_for_security_test=False, suitable_for_feishu_demo=False, suitable_for_presentation_story=False,
         required_product_modules=["规则引擎（待 Amex 原文）"],
         recommended_demo_steps=[],
         expected_agent_questions=["Amex 案件怎么处理？"], expected_agent_actions=["说明 Amex 规则待确认"],
         expected_system_blockers=["Amex 规则未确认时禁止自动判责"], acceptance_assertions=["明确提示规则未确认"]),
    core=False, related=["CB-CASE-032", "CB-CASE-033"]))
