# -*- coding: utf-8 -*-
"""来源登记、冲突清单、数据缺口清单 —— OceanPilot 拒付案例库构建元数据。"""

SOURCES = [
    {
        "source_id": "SRC-01",
        "file_name": "merchants-dispute-management-guidelines.pdf",
        "sha256": "5505594a9ae3a062c84a85294adcf5c621ac80d292f5ab7e0c24bd2b26a16cd4",
        "file_type": "PDF (version 1.6, zip deflate encoded)",
        "pages_or_lines": "67 页 / 提取文本 2819 行",
        "document_title": "Dispute Management Guidelines for Visa Merchants June 2024",
        "publisher_or_author": "Visa（PDF 元数据 /Author: Visa；InDesign 排版）",
        "publish_or_version": "标题标注 June 2024；元数据创建 2023-06-03、修改 2024-08-01",
        "scheme": "Visa",
        "region": "全球（正文含欧洲、美国等地区差异条款）",
        "possible_outdated": "是——正文含 2024-04-13 / 2024-10-19 生效的规则变更；VAMP（2025 起）已取代本指南第 10.5 节所述 VFMP（依据 SRC-03 第 18 节）",
        "read_complete": "是（PAGE 1-67 全部读取）",
        "unreadable_parts": "P18 披露示例图片不在文本层；P9 生命周期图为图形；P54-58 Compelling Evidence 表格为跨页多栏排版，逐格对应建议对照 PDF 原版",
        "ocr_used": "否（文字层完整，无低文本页）",
        "toc_appendix_tables": "含目录、Compelling Evidence 表、Glossary（P60-66）",
    },
    {
        "source_id": "SRC-02",
        "file_name": "chargeback-guide.pdf",
        "sha256": "77f7db1b7edaf18204a706d6322a0b07d2638323087e9b42ea7926298dbeb5c3",
        "file_type": "PDF (version 1.5)",
        "pages_or_lines": "1582 页 / 提取文本 67659 行",
        "document_title": "Chargeback Guide Merchant Edition",
        "publisher_or_author": "Mastercard（Antenna House / AH XSL Formatter 生成）",
        "publish_or_version": "19 May 2026（页脚标注）",
        "scheme": "Mastercard",
        "region": "全球 + 区域专章（中国大陆、南非、美国境内、欧洲、尼日利亚、哥斯达黎加、哈萨克斯坦、坦桑尼亚、波兰等）",
        "possible_outdated": "风险中等——正文含多个未来生效日（如 TLID 2026-06-02）；预仲裁章节已并入 Ch2/Ch3（Ch5 整章删除）",
        "read_complete": "是（11 个连续分块覆盖行 1-67659，即 PAGE 1-1582）",
        "unreadable_parts": "P35 生命周期总览图为图形不在文本层；Appendix A CVM 限额数值在外部 Excel（CVM_Limit_Amounts.xls），正文未载；原文个别句子缺数字/拼写瑕疵已逐处记录（见 10_conflicts_and_data_gaps.md）",
        "ocr_used": "否（文字层完整，无低文本页）",
        "toc_appendix_tables": "含 30 页目录、Appendix A-E、多张时限/责任表",
    },
    {
        "source_id": "SRC-03",
        "file_name": "卡组织争议处理规则与案例映射.md",
        "sha256": "a5f0730175ae33060faafe3d78fe93ee4cd50f7f5d3631a54cc4e14c19408d86",
        "file_type": "Markdown（UTF-8）",
        "pages_or_lines": "703 行",
        "document_title": "卡组织争议处理规则与争议案例资料汇总（修订版）",
        "publisher_or_author": "未注明（团队内部二次整理稿）",
        "publish_or_version": "无版本号/日期；文中含「截至 2026 年 8 月」的 VAMP 描述",
        "scheme": "Visa / Mastercard / American Express（含 Discover、JCB、UnionPay 简述）",
        "region": "多地区（文中标注地区差异）",
        "possible_outdated": "是——属二手整理资料，需与卡组织正式 Standards 及收单机构收到的有效版本核对",
        "read_complete": "是（1-703 行全部读取）",
        "unreadable_parts": "无；但文中第 28/29 节 ODPM 映射表引用外部文件 ODPM商户申诉字段.xlsx，该文件不在工作区，无法核对",
        "ocr_used": "否",
        "toc_appendix_tables": "29 个章节 + 2 张 ODPM 映射表",
    },
]

CONFLICTS = [
    {
        "conflict_id": "CONFLICT-001",
        "topic": "Visa Condition 11.3 与 12.1 的版本切换",
        "description": "Visa 指南：No Authorization/Late Presentment 于 2024-04-13 起使用 11.3，此前使用 12.1 Late Presentment；系统需按交易日期选码。",
        "sources": ["SRC-01 P2/P9/P31-32"],
        "possible_reason": "规则版本切换，非错误",
        "status": "NEEDS_CONFIRMATION（落库需带 effective_date）",
    },
    {
        "conflict_id": "CONFLICT-002",
        "topic": "Visa 12.6 编号歧义",
        "description": "目录将 Duplicate Processing 与 Paid by Other Means 均列为 Condition 12.6；正文实际使用 12.6.1 / 12.6.2。",
        "sources": ["SRC-01 P2/P37-38"],
        "possible_reason": "文档排版/编号方式",
        "status": "NEEDS_CONFIRMATION",
    },
    {
        "conflict_id": "CONFLICT-003",
        "topic": "Visa 10.4 历史交易窗口口径",
        "description": "P26 先写“settled 120 calendar days prior to the dispute”，随后要求“settled between 120–365 calendar days prior to the dispute processing date”。",
        "sources": ["SRC-01 P26"],
        "possible_reason": "同一规则的两种表述，需以 Visa Rules 为准",
        "status": "CONFLICTING_SOURCES",
    },
    {
        "conflict_id": "CONFLICT-004",
        "topic": "Mastercard POI 原因码 4834 vs 4831",
        "description": "Chapter 2 目录为 Point-of-Interaction Error (4834/34)，Chapter 4 目录为 (4831)；正文将 4831 标注为将被淘汰的过渡码。",
        "sources": ["SRC-02 目录 P11/P25；正文 P691-692、P1324"],
        "possible_reason": "章节模板版本差异 + 编码合并过渡",
        "status": "NEEDS_CONFIRMATION",
    },
    {
        "conflict_id": "CONFLICT-005",
        "topic": "Mastercard 淘汰码清单",
        "description": "4807/4812/4855/4841/4859/4860（及 SMS 41/55/59/60、4831、4846）标注 will eventually be eliminated，但正文消息文本模板仍列作可选项。",
        "sources": ["SRC-02 P64/P83/P116/P172/P182/P221/P256/P313 等"],
        "possible_reason": "编码合并进行中（旧码并入 4853/4834）",
        "status": "NEEDS_CONFIRMATION（系统需建编码合并映射表）",
    },
    {
        "conflict_id": "CONFLICT-006",
        "topic": "Mastercard Second Presentment 时限 45 vs 30 天",
        "description": "Chapter 2 多数节为 45 天，但 Stand-in/X-Code 的 Refund previously issued（P104）与 CAT 3 的 Authorization was not required（P119）写 30 天；Chapter 4 通用模板为 30 天、4837 节为 45 天；失败旅行商户节为 45 天。",
        "sources": ["SRC-02 P66/P104/P119/P929/P1001/P1207"],
        "possible_reason": "章节模板新旧版本混杂",
        "status": "CONFLICTING_SOURCES（不可直接转为生产规则）",
    },
    {
        "conflict_id": "CONFLICT-007",
        "topic": "Mastercard 预仲裁响应 15 vs 30 天",
        "description": "通用章节收单行响应 15 天；Change of Reason 章节 30 天且无动作 30 天后自动接受。",
        "sources": ["SRC-02 P931/P944-945/P1305-1306"],
        "possible_reason": "Change of Reason 专项规则或模板差异",
        "status": "NEEDS_CONFIRMATION",
    },
    {
        "conflict_id": "CONFLICT-008",
        "topic": "Mastercard 仲裁提交 10 vs 15 天",
        "description": "通用 10 天自 Rejected Date；Change of Reason 章节 15 天。",
        "sources": ["SRC-02 P932/P947/P1307"],
        "possible_reason": "同上",
        "status": "NEEDS_CONFIRMATION",
    },
    {
        "conflict_id": "CONFLICT-009",
        "topic": "4871 章节仲裁消息文本写 4870/70",
        "description": "4871（NRI 芯片责任转移）章节的仲裁 Message text 要求写 “Chip Liability Shift, 70, 4870”，疑为复用 4870 章节模板的残留。",
        "sources": ["SRC-02 P635-636"],
        "possible_reason": "文档复制残留",
        "status": "CONFLICTING_SOURCES",
    },
    {
        "conflict_id": "CONFLICT-010",
        "topic": "原文两处缺数字",
        "description": "P248 失败旅游商户预仲裁“after calendar days”缺数字（对照 P229 为 15 天）；P1020 同类句子缺 15。",
        "sources": ["SRC-02 P229/P248/P1007/P1020"],
        "possible_reason": "源文档缺陷",
        "status": "NEEDS_CONFIRMATION",
    },
    {
        "conflict_id": "CONFLICT-011",
        "topic": "附录 F 引用不存在",
        "description": "正文 P38 引用 Appendix F Fee Collection；P1430/P1486 引用 Appendix F，但文档只有附录 A-E。",
        "sources": ["SRC-02 P38/P1430/P1486"],
        "possible_reason": "引用未更新",
        "status": "NEEDS_CONFIRMATION",
    },
    {
        "conflict_id": "CONFLICT-012",
        "topic": "Visa 商户响应天数缺失",
        "description": "Visa 指南对争议响应各步只写“每步有时限，视收单而定”，未给具体天数；Mastercard 指南给出明确天数。两者体系不同，不得把 MC 天数套用到 Visa。",
        "sources": ["SRC-01 P12；SRC-02 各章"],
        "possible_reason": "卡组织披露习惯差异",
        "status": "CONFLICTING_SOURCES",
    },
    {
        "conflict_id": "CONFLICT-013",
        "topic": "Visa VFMP（10.5）已被 VAMP 取代",
        "description": "Visa 指南 P28 仍描述 Visa Fraud Monitoring Program（VFMP）；SRC-03 第 18 节称 2025 年起 VAMP 全面取代 VFMP/VDMP。",
        "sources": ["SRC-01 P28；SRC-03 §18"],
        "possible_reason": "指南出版时间（June 2024）早于 VAMP 生效",
        "status": "CONFLICTING_SOURCES（版本时效）",
    },
    {
        "conflict_id": "CONFLICT-014",
        "topic": "卡组织分类体系不可一一映射",
        "description": "Visa Condition（10.x-13.x）与 Mastercard Message Reason Code（4853 等）与 Amex Reason Code（C04/C05/C08/C31/C32）为多对多映射；生命周期阶段也不同（Visa Dispute/Response/Pre-Arb/Arb vs MC First CB/Second Presentment/Pre-Arb/Arb vs Amex Inquiry/CB/Reversal）。",
        "sources": ["SRC-03 §1/§28/§29"],
        "possible_reason": "卡组织体系差异",
        "status": "CONFLICTING_SOURCES（不可合并为统一生产规则）",
    },
    {
        "conflict_id": "CONFLICT-015",
        "topic": "ODPM 映射表中带 * 的近似映射",
        "description": "SRC-03 §28 中多条 ODPM 原因到卡组织编码的映射标注为近似（如编号 3、6、62、79），编号 73 中英文含义不一致；BNPL/DCB/KakaoPay 渠道无卡组织编码。",
        "sources": ["SRC-03 §28"],
        "possible_reason": "渠道差异 + 整理稿未与业务方核对",
        "status": "NEEDS_CONFIRMATION",
    },
]

DATA_GAPS = [
    {"gap_id": "GAP-001", "gap": "Visa 指南未给出争议响应/预仲裁/仲裁各步的具体天数", "why_matters": "OceanPilot 的截止时间计算与提醒功能需要天数参数", "resolution": "以收单机构收到的 Visa 有效版本为准，业务人员确认后录入规则引擎"},
    {"gap_id": "GAP-002", "gap": "Mastercard Appendix A 的 CVM 限额数值在外部 Excel，正文未载", "why_matters": "4837 不可拒付判定（≤CVM 限额非接触交易）依赖该数值", "resolution": "下载 CVM_Limit_Amounts.xls 并导入规则库"},
    {"gap_id": "GAP-003", "gap": "三份资料均不含真实商户的完整判例（卡号/订单号/结局俱全的案件）", "why_matters": "Sandbox 需要贴近真实的数据", "resolution": "用 SYNTHETIC_DEMO 合成，且不得宣称真实"},
    {"gap_id": "GAP-004", "gap": "ODPM商户申诉字段.xlsx 不在工作区", "why_matters": "SRC-03 §28/§29 的两张映射表源自该文件，无法核对原始 47 条原因与申诉元素代码", "resolution": "向业务方索要该 Excel 并复核映射表"},
    {"gap_id": "GAP-005", "gap": "Amex 的完整规则原文不在三份文件中（仅 SRC-03 二手映射）", "why_matters": "C 系列编码的证据要求、时限未获官方原文支撑", "resolution": "获取 Amex Merchant Regulations 原文后再落库 C 系列规则"},
    {"gap_id": "GAP-006", "gap": "卡组织仲裁费的金额未在三份文件中给出", "why_matters": "费用测算与接受/抗辩决策依赖费用", "resolution": "从收单机构费率表确认"},
    {"gap_id": "GAP-007", "gap": "原文没有各场景的“胜诉概率”数据", "why_matters": "产品不应展示无依据的胜率", "resolution": "仅用历史案件数据估计，或只展示证据完整度"},
    {"gap_id": "GAP-008", "gap": "三份资料未覆盖 Discover/JCB/UnionPay 详细规则", "why_matters": "第一期只做 Visa/MC/Amex 时无影响，二期扩展需要", "resolution": "二期再补对应规则文档"},
    {"gap_id": "GAP-009", "gap": "飞书提醒、人工审核等 OceanPilot 内部流程在三份文件中不存在", "why_matters": "产品流程无法从资料推导，只能作为项目合成设计", "resolution": "以 SYNTHETIC_DEMO 设计，标注为项目自定流程"},
    {"gap_id": "GAP-010", "gap": "拒付通知到达商户的准确时间（上游回传延迟）无资料支撑", "why_matters": "临近截止的提醒时机需要估计", "resolution": "与上游收单系统联调时实测"},
]
