const RUNTIME_LABEL={DEEPSEEK_LIVE:"DeepSeek Live",CLAUDE_LIVE:"Claude Live",INJECTED_MODEL:"Injected Model",OFFLINE_FALLBACK:"Offline Fallback"};
const TRACE_STATUS={COMPLETED:"已完成",WAITING:"等待人工",BLOCKED:"已阻断"};
function fillAgentPrompt(text){$('agentMessage').value=text;$('agentMessage').focus();}
function traceClass(step){if(step.status==='BLOCKED')return'blocked';if(step.actor==='HumanGate')return'human';if(step.actor==='CaseTool'||step.source==='DETERMINISTIC_FALLBACK'||step.source==='CASE_STATE')return'rule';return'ai';}
function factChips(items,pending=false){return items&&items.length?`<div class="fact-chips">${items.map(item=>`<span class="fact-chip${pending?' pending':''}">${esc(item)}</span>`).join('')}</div>`:'<span class="faint">无</span>';}
function renderAgentHistory(){const out=$('agentHistory');out.innerHTML=S.agentMessages.length?S.agentMessages.slice(-8).map(item=>`<div class="chat-bubble ${item.role}">${esc(item.text)}</div>`).join(''):'<div class="chat-bubble assistant">进入案件后，AI 会基于当前快照自动分析。</div>';out.scrollTop=out.scrollHeight;}
function appendAgentMessage(role,text){S.agentMessages.push({role,text});renderAgentHistory();}
function acceptAgentUserMessage(message){S.lastAgentInput=message;appendAgentMessage('user',message);const input=$('agentMessage');if(input.value.trim()===message)input.value='';}
async function bindAgentCase(caseId,reset=false){if(S.caseId!==caseId)return false;const context=caseContext.capture();const ticket=OceanRequest.begin('agent-bind');const result=await api('GET',`/cases/${caseId}`);if(!result.ok||!OceanRequest.isLatest(ticket)||!caseContext.isCurrent(context,false)||!acceptCaseSnapshot(result.data))return false;S.agentBoundCaseId=caseId;$('agentCaseContext').textContent=`${caseId.slice(0,8)}… · ${(STATUS_VIEW[result.data.phase]||['待处理'])[0]}`;if(reset){S.agentMessages=[];S.pendingReview=null;S.pendingAgentTurn=null;appendAgentMessage('assistant',`已绑定案件 ${caseId.slice(0,8)}…。后续提问不会重复建案。`);$('agentOutput').innerHTML='<div class="empty-state"><strong>案件上下文已就绪</strong><p>AI 正在读取当前案件快照。</p></div>';}return true;}
async function selectAgentCase(caseId){await openStoredCase(caseId);}
function agentAction(data){const a=data.recommended_action||{};if(a.kind==='OPEN_EVIDENCE_MODAL'&&a.evidence_code)return `<div class="agent-action"><p>${esc(a.label||'补交下一项资料')} · 需要操作人员明确确认</p><button class="tbtn primary" onclick="openEvidenceModalForCase('${esc(data.case_id)}','${esc(a.evidence_code)}','${esc(a.evidence_label||EVIDENCE_LABEL[a.evidence_code]||a.evidence_code)}')">${esc(a.label||'打开资料提交')}</button></div>`;if(a.kind==='OPEN_CASE_DETAIL')return `<div class="agent-action"><p>${esc(a.label||'查看案件详情')} · Agent 不会自动修改案件</p><button class="tbtn" onclick="openStoredCase('${esc(data.case_id)}')">打开案件详情</button></div>`;return'';}
function reviewStatusLabel(status){return({UNREVIEWED:'待人工审核',NEEDS_MORE_INFO:'待补资料',APPROVED:'审核已通过',REJECTED:'审核已驳回'})[status]||status||'待人工审核';}
function agentMaterials(items){return items&&items.length?`<div class="agent-materials">${items.map(item=>`<div class="agent-material"><strong>${esc(item.label)}</strong><span>${esc(item.summary)}</span></div>`).join('')}</div>`:'<span class="faint">尚无已登记材料</span>';}
function agentCitations(items,data){return items&&items.length?`<div class="agent-citations">${items.map(item=>`<div class="agent-citation"><strong>${esc(item.title)}</strong><p>${esc(item.claim)}</p><p>${esc(item.verification_status)} · ${esc(item.limitation)}</p><button class="tbtn" onclick="showRuleReference('${esc(item.reference_id)}',{sourceView:'diagnosis',caseId:'${esc(data.case_id)}',cardNetwork:'${esc(data.card_network||S.cardNetwork)}'})">查看引用 ${esc(item.reference_id)}</button></div>`).join('')}</div>`:'<span class="faint">当前尚无已核验引用；系统不会匹配相似条款。</span>';}
function agentReviewProposal(data){const proposal=data.review_proposal;if(!proposal){S.pendingReview=null;return'';}S.pendingReview={caseId:data.case_id,sourceTurnId:data.source_turn_id,caseRevision:data.case_revision,status:proposal.status};const conflicts=proposal.conflicts||[];return `<div class="review-proposal" id="agentReviewProposal"><h4>拟写入案件 · ${esc(reviewStatusLabel(proposal.status))}</h4><p>${esc(proposal.summary)}</p>${conflicts.length?`<p><b>一致性阻断：</b>${conflicts.map(esc).join('；')}</p>`:''}<p><b>下一步：</b>${esc(proposal.next_action)}<br><b>原因：</b>${esc(proposal.why)}</p><input id="agentReviewerId" aria-label="审核确认人" value="judge_reviewer_01" placeholder="审核人 Actor ID"><div class="actions"><button class="tbtn primary" id="confirmAgentReviewButton" onclick="confirmAgentReview()">确认写入案件</button><button class="tbtn" onclick="editAgentReview()">修改输入</button><button class="tbtn" onclick="cancelAgentReview()">取消</button></div><div id="agentReviewReceipt" aria-live="polite"></div></div>`;}
function agentReviewDecision(data){const decision=data.review_decision;if(!decision)return'';return `<div class="review-receipt"><b>${esc(reviewStatusLabel(decision.status))}</b> · revision ${esc(decision.revision)}<br>审核人 ${esc(decision.confirmed_by)} · 审计 ${esc(decision.audit_event_id)}</div>`;}
function renderAgentTurn(data){const j=data.judgment||{},runtime=data.runtime||{},trace=data.agent_trace||[];const mode=RUNTIME_LABEL[runtime.mode]||runtime.mode||'Unknown Runtime';const badge=$('agentRuntimeBadge');badge.textContent=`${mode} · ${runtime.model||'unknown'}`;badge.className=`pill runtime-badge ${runtime.mode==='OFFLINE_FALLBACK'?'p-warn':'p-good'}`;appendAgentMessage('assistant',data.assistant_message);
  const human=j.human_gate?'<span class="pill p-warn">需要人工确认</span>':'<span class="pill p-good">当前无需人审</span>';
  $('agentOutput').innerHTML=`<div class="assistant-message"><span>AI Assistant · ${esc(mode)}</span><p>${esc(data.assistant_message)}</p></div>`
    +`<div class="agent-result-grid"><section class="agent-panel"><div class="agent-panel-hd"><h3>AI 判断总结</h3><span class="pill p-acc">${esc(reviewStatusLabel(data.review_status))}</span></div><div class="agent-panel-bd"><p class="judgment-summary">${esc(data.analysis_summary||j.decision_summary)}</p>`
    +`<div class="judgment-row"><span>分析触发</span><strong>${esc(data.trigger)} · revision ${esc(data.case_revision)}</strong></div>`
    +`<div class="judgment-row"><span>问题类型</span><strong>${esc(j.problem_type)}</strong></div><div class="judgment-row"><span>已确认事实</span>${factChips(j.confirmed_facts)}</div><div class="judgment-row"><span>待确认事实</span>${factChips(j.uncertain_facts,true)}</div>`
    +`<div class="judgment-row"><span>材料就绪度</span><strong>${esc(j.evidence_readiness)}</strong></div><div class="judgment-row"><span>材料内容</span>${agentMaterials(data.material_contents)}</div><div class="judgment-row"><span>责任域</span><strong>${esc(TEAM_LABEL[j.responsible_team]||j.responsible_team)}</strong></div><div class="judgment-row"><span>判断原因</span><strong>${esc(data.decision_reason)}</strong></div><div class="judgment-row"><span>人工边界</span><strong>${human}</strong></div><div class="judgment-row"><span>下一步</span><strong>${esc(j.next_action)}</strong></div><div class="judgment-row"><span>引用</span>${agentCitations(data.citations,data)}</div>`
    +`${agentAction(data)}${agentReviewDecision(data)}${agentReviewProposal(data)}</div></section>`
    +`<section class="agent-panel"><div class="agent-panel-hd"><h3>Agent 可视化执行轨迹</h3><span class="pill p-mut">不展示思维链</span></div><div class="agent-panel-bd agent-trace">${trace.map(step=>`<div class="trace-step ${traceClass(step)}"><div class="trace-top"><strong>${esc(step.step)} · ${esc(step.actor)}</strong><span>${esc(TRACE_STATUS[step.status]||step.status)}</span></div><p>${esc(step.action)}</p><div class="trace-meta">${esc(step.source)} · ${esc(step.output_summary)}</div></div>`).join('')}</div></section></div>`;}
async function runAgentTurn(message,trigger='USER_MESSAGE',showUser=false){const statusEl=$('agentTurnStatus');if(!S.agentCase){statusEl.className='copilot-status error';statusEl.setAttribute('role','alert');statusEl.textContent='案件上下文尚未就绪，请稍后重试。';return false;}const caseId=S.agentCase.case_id;if(S.agentSubmitting){if(S.pendingAgentTurn&&S.pendingAgentTurn.trigger==='USER_MESSAGE'){if(trigger!=='USER_MESSAGE')return true;statusEl.className='copilot-status error';statusEl.setAttribute('role','alert');statusEl.textContent='已有一条人工输入等待分析；当前输入已保留，请稍后再次发送。';return false;}if(showUser)acceptAgentUserMessage(message);S.pendingAgentTurn={message,trigger,caseId};statusEl.className='copilot-status';statusEl.setAttribute('role','status');statusEl.textContent=trigger==='USER_MESSAGE'?'你的输入已排队，将在当前分析完成后自动发送。':'案件状态已更新，将在当前分析完成后自动重新分析。';return true;}if(showUser)acceptAgentUserMessage(message);const context=caseContext.capture();S.agentSubmitting=true;const button=$('agentSendButton');const userTurn=trigger==='USER_MESSAGE';button.disabled=userTurn;button.textContent=userTurn?'Agent 正在分析…':'分析中 · 可排队发送';statusEl.className='copilot-status';statusEl.setAttribute('role','status');statusEl.textContent='正在读取案件快照、规则引用与审核状态…';const payload={message,locale:S.loc==='en'?'en-US':'zh-CN',case_id:caseId,trigger};if(S.cardNetwork)payload.card_network=S.cardNetwork;
  try{const result=await requestJson('',"POST","/api/v1/agent/turns",payload);if(!caseContext.isCurrent(context))return true;if(!result.ok){statusEl.className='copilot-status error';statusEl.setAttribute('role','alert');statusEl.textContent=result.status===422?'输入包含无效或敏感内容，请移除后重试。':'请求未完成，请重试。';appendAgentMessage('assistant','本轮请求没有完成，案件状态未被修改。');return true;}if(S.agentCase&&result.data.case_id===caseId&&result.data.case_revision===S.caseRevision){renderAgentTurn(result.data);statusEl.textContent=`已分析案件 ${result.data.case_id} · revision ${result.data.case_revision}${result.data.result==='REPLAYED'?' · 重放快照':''}`;}await loadCases();return true;}
  finally{S.agentSubmitting=false;button.disabled=false;button.textContent='发送给 Agent';const pending=S.pendingAgentTurn;S.pendingAgentTurn=null;if(pending&&S.agentCase&&S.agentCase.case_id===pending.caseId)await runAgentTurn(pending.message,pending.trigger,false);}}
async function sendAgentTurn(){const message=$('agentMessage').value.trim();const statusEl=$('agentTurnStatus');if(message.length<3){statusEl.className='copilot-status error';statusEl.setAttribute('role','alert');statusEl.textContent='请至少输入 3 个字符，再交给 AI 分析。';$('agentMessage').focus();return;}await runAgentTurn(message,'USER_MESSAGE',true);}
async function analyzeCurrentCase(trigger){const messages={CASE_OPENED:'请基于当前案件快照总结状态、材料、判断原因、下一步及其依据。',REASON_CONFIRMED:'争议原因已由操作人员确认，请基于新版本重新分析。',EVIDENCE_SUBMITTED:'新资料已明确提交，请重新核对材料缺口、判断和下一步。',EVIDENCE_WITHDRAWN:'最近一项资料已明确撤回，请基于当前版本重新判断缺口并清除过期结论。',REVIEW_CONFIRMED:'审核决定已由操作人员确认写入，请说明当前状态和后续人工闸门。'};await runAgentTurn(messages[trigger]||messages.CASE_OPENED,trigger,false);}
function cancelAgentReview(){S.pendingReview=null;const card=$('agentReviewProposal');if(card)card.remove();$('agentTurnStatus').textContent='已取消本次拟写入提案；案件状态未改变。';}
function editAgentReview(){const text=S.lastAgentInput||'审核通过，已核对全部 Synthetic 材料内容一致。';cancelAgentReview();$('agentMessage').value=text;$('agentMessage').focus();}
async function confirmAgentReview(){const pending=S.pendingReview;if(!pending)return;const context=caseContext.capture();const actor=$('agentReviewerId').value.trim();const receipt=$('agentReviewReceipt');if(!actor){receipt.className='form-error';receipt.textContent='请填写审核确认人 Actor ID。';return;}const button=$('confirmAgentReviewButton');button.disabled=true;button.textContent='正在写入…';const result=await requestJson('',"POST",`/api/v1/agent/cases/${encodeURIComponent(pending.caseId)}/review-decisions`,{source_turn_id:pending.sourceTurnId,case_revision:pending.caseRevision,confirmed_by:actor});if(!caseContext.isCurrent(context,false))return;if(!result.ok){receipt.className='form-error';receipt.textContent=result.status===409?'案件版本已经变化，请重新分析后再确认。':'审核决定未写入，请检查后重试。';button.disabled=false;button.textContent='确认写入案件';return;}receipt.className='review-receipt';receipt.textContent=`${result.data.result==='REPLAYED'?'已重放':'已写入'}审核决定 · 审计 ${result.data.audit_event_id}`;appendAgentMessage('assistant',`审核决定已写入案件，审计编号 ${result.data.audit_event_id}。`);S.pendingReview=null;const fresh=await api('GET',`/cases/${pending.caseId}`);if(fresh.ok&&caseContext.isCurrent(context,false)&&acceptCaseSnapshot(fresh.data))renderStoredDiagnosis(fresh.data);if(await bindAgentCase(pending.caseId,false))await analyzeCurrentCase('REVIEW_CONFIRMED');}
$('agentMessage').addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'){event.preventDefault();sendAgentTurn();}});
