function safeHttpUrl(value){try{const url=new URL(value);return['http:','https:'].includes(url.protocol)?url.href:'#';}catch(error){return'#';}}
function ruleDetailPath(ruleVersionId){return `/rules/${encodeURIComponent(String(ruleVersionId||''))}`;}
function renderCaseRule(c){
  const ref=c.rule_reference||{};
  if(ref.match_status!=='EXACT_MATCH'||!ref.rule_version_id){
    $('diagnosisRuleReferenceOut').innerHTML='<div class="note"><b>未解析到精确匹配规则。</b><br>当前卡组织与争议原因没有正式可引用的精确映射；不会把默认模板或相似条款当作正式依据。规则适用性需要人工核验。</div>';return;
  }
  const source=safeHttpUrl(ref.source_url);
  $('diagnosisRuleReferenceOut').innerHTML=`<h3>${esc(NETWORK_LABEL[ref.scheme]||ref.scheme||c.card_network)} ${esc(ref.scheme_reason_code)} · ${esc(ref.display_name||c.reason_label)}</h3><div class="row"><span class="pill p-warn">${esc(ref.verification_status||'未核验')}</span><span class="pill p-mut">${esc(ref.rule_version||'版本待核验')}</span></div><div class="kv"><span class="k">来源</span><span>${esc(ref.source_document||'待核验')} · ${esc(ref.source_section||'章节待核验')}</span></div><div class="actions"><button class="tbtn" onclick="showRuleReference('${esc(ref.rule_version_id)}')">查看具体规则版本</button>${source!=='#'?`<a class="tbtn" href="${esc(source)}" target="_blank" rel="noopener noreferrer">打开原始来源 ↗</a>`:''}</div><div class="note">${esc(ref.limitation||'仅为公开规则整理摘要，正式适用性需人工确认。')}</div>`;
}
function ruleReturnButton(){return S.caseId?'<button class="tbtn" onclick="returnFromRuleReference()">返回原案件</button>':'';}
function markRuleSelection(ruleVersionId){document.querySelectorAll('#ruleRows tr[data-rule-version-id]').forEach(row=>row.classList.toggle('rule-selected',row.dataset.ruleVersionId===ruleVersionId));}
async function loadRules(){const requestId=++S.rulesRequestId;S.ruleDetailRequestId++;const params=new URLSearchParams();const scheme=$('ruleScheme').value;const query=$('ruleSearch').value.trim();if(scheme)params.set('scheme',scheme);if(query)params.set('q',query);
  const suffix=params.toString()?`?${params.toString()}`:'';const result=await api('GET',`/rules${suffix}`);if(requestId!==S.rulesRequestId)return;const data=result.data||{};const detail=$('ruleDetail');
  if(!result.ok||!Array.isArray(data.items)){S.rules=[];S.currentRuleId=null;$('ruleStats').textContent='规则库暂不可用';$('ruleRows').innerHTML='<tr><td colspan="6"><div class="error-state"><strong>无法读取规则目录</strong><br>请稍后重试；页面不会回退到伪造数据。</div></td></tr>';detail.classList.remove('reference-highlight');detail.innerHTML='<div class="panel-hd"><h2>规则详情</h2></div><div class="panel-bd"><div class="error-state"><strong>规则库暂不可用</strong><br>没有使用缓存或伪造详情。</div></div>';$('crumbId').textContent='规则目录';return;}
  S.rules=data.items;$('ruleDisclaimer').textContent=data.disclaimer||$('ruleDisclaimer').textContent;$('ruleStats').textContent=`${data.total} 条 · ${data.demo_mapped} 条 Demo Mapped · ${data.scheme_count} 个卡组织 · ${data.source_document_count} 份来源`;
  $('ruleRows').innerHTML=S.rules.map(rule=>`<tr data-rule-version-id="${esc(rule.rule_version_id)}"><td><div class="rule-id">${esc(rule.rule_version_id)}</div><div class="rule-name">${esc(rule.scheme_reason_code)} · ${esc(rule.display_name)}</div></td><td>${esc(rule.scheme)}</td><td>${esc(rule.version_label||'未标定')}</td><td><span class="pill ${rule.demo_role==='DEMO_MAPPED'?'p-good':'p-mut'}">${esc(rule.demo_role)}</span></td><td><span class="pill p-acc">${esc(rule.verification_status)}</span></td><td><button class="tbtn" onclick="openRule('${esc(rule.rule_version_id)}')">查看详情</button></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty-state"><strong>没有匹配规则</strong><p>请调整卡组织或搜索条件。</p></div></td></tr>';
  if(S.currentRuleId&&S.rules.some(rule=>rule.rule_version_id===S.currentRuleId)){await openRule(S.currentRuleId);return;}S.currentRuleId=null;markRuleSelection(null);detail.classList.remove('reference-highlight');$('crumbId').textContent='规则目录';detail.innerHTML='<div class="panel-hd"><h2>规则详情</h2><span class="pill p-acc">Provenance</span></div><div class="panel-bd"><div class="empty-state"><strong>选择当前列表中的规则</strong><p>筛选已更新；旧详情已清除，避免列表与来源错配。</p></div></div>';}
async function openRule(ruleVersionId){const requestId=++S.ruleDetailRequestId;const detail=$('ruleDetail');const result=await api('GET',ruleDetailPath(ruleVersionId));if(requestId!==S.ruleDetailRequestId)return;const data=result.data||{};
  if(!result.ok){S.currentRuleId=null;markRuleSelection(null);detail.classList.remove('reference-highlight');$('crumbId').textContent='规则目录';const message=result.status===503?'规则数据库暂不可用。':'该规则版本不存在。';detail.innerHTML=`<div class="panel-hd"><h2>规则详情</h2></div><div class="panel-bd"><div class="error-state"><strong>无法读取规则详情</strong><br>${message} 旧详情已清除。</div></div>`;return;}
  S.currentRuleId=data.rule_version_id;writeNavigation(true);markRuleSelection(data.rule_version_id);$('crumbId').textContent=data.rule_version_id;const requirementList=items=>(items||[]).map(item=>`<div class="requirement"><span class="seq">${esc(item.sequence)}</span><div><strong>${esc(item.description_zh)}</strong><span>${esc(item.necessity)}${item.internal_evidence_code?` · 内部映射 ${esc(item.internal_evidence_code)}`:''}</span></div></div>`).join('')||'<div class="empty">无</div>';const sourceUrl=safeHttpUrl(data.document&&data.document.source_url);
  detail.innerHTML=`<div class="panel-hd"><h2>规则详情</h2><div class="grow"></div>${ruleReturnButton()}<span class="pill p-acc">${esc(data.verification_status)}</span></div><div class="panel-bd"><div class="rule-id">${esc(data.rule_version_id)}</div><h2>${esc(data.scheme)} ${esc(data.scheme_reason_code)} · ${esc(data.display_name)}</h2><div class="row"><span class="pill ${data.demo_role==='DEMO_MAPPED'?'p-good':'p-mut'}">${esc(data.demo_role)}</span><span class="pill p-mut">${esc(data.region)}</span><span class="pill p-mut">${esc(data.version_label||'版本未标定')}</span></div><div class="rule-section"><h3>来源与适用范围</h3><div class="kv"><span class="k">文档</span><span>${esc(data.document&&data.document.title)}</span></div><div class="kv"><span class="k">章节</span><span>${esc(data.source_section||'未核验')}</span></div><div class="kv"><span class="k">生效日期</span><span>${esc(data.effective_date||'未核验')}</span></div><div class="kv"><span class="k">来源链接</span><span>${sourceUrl==='#'?esc(data.document&&data.document.source_url):`<a href="${esc(sourceUrl)}" target="_blank" rel="noopener noreferrer">打开来源文档</a>`}</span></div>${data.internal_window_days==null?'':`<div class="kv"><span class="k">内部 Demo 窗口</span><span>${esc(data.internal_window_days)} 天（非官方响应期限）</span></div>`}</div><div class="rule-section"><h3>Required Assertions</h3>${requirementList(data.assertions)}</div><div class="rule-section"><h3>卡组织打包证据摘要 · ${(data.evidence||[]).length} 项</h3>${requirementList(data.evidence)}</div><div class="rule-section"><h3>限制与免责声明</h3><div class="note">${esc(data.limitation)}<br><br>${esc(data.disclaimer)}</div></div></div>`;
  detail.classList.remove('reference-highlight');requestAnimationFrame(()=>{if(S.currentRuleId!==data.rule_version_id)return;detail.classList.add('reference-highlight');detail.focus({preventScroll:true});detail.scrollIntoView({block:'start',behavior:'auto'});setTimeout(()=>{if(S.currentRuleId===data.rule_version_id)detail.classList.remove('reference-highlight');},1600);});}
function showRuleReference(ruleVersionId){
  if(!ruleVersionId)return;
  S.ruleReturnContext=S.caseId?{caseId:S.caseId,section:S.section}:null;
  S.currentRuleId=String(ruleVersionId);$('ruleSearch').value='';$('ruleScheme').value='';showView('rules');
}
async function returnFromRuleReference(){
  const context=S.ruleReturnContext||(S.caseId?{caseId:S.caseId,section:'rules'}:null);
  if(!context){showView('overview');return;}
  S.section=context.section||'rules';S.ruleReturnContext=null;
  if(S.caseId!==context.caseId||!S.caseSnapshot)await openStoredCase(context.caseId);
  else{await refreshCase();showView('workspace');}
}
