function currentCardNetwork(){return $('network')?$('network').value:S.cardNetwork;}
function ruleReferenceTarget(sourceView='flow'){const view=sourceView==='diagnosis'?'diagnosis':'flow';const input=$(view==='diagnosis'?'diagnosisNetwork':'network');const caseId=view==='diagnosis'?(S.selectedCase&&S.selectedCase.case_id):S.caseId;return{sourceView:view,caseId:String(caseId||''),cardNetwork:String(input?input.value:S.cardNetwork||'').toUpperCase(),outputId:view==='diagnosis'?'diagnosisRuleReferenceOut':'ruleReferenceOut'};}
async function setRuleReferenceNetwork(sourceView,value){const selected=String(value||'').toUpperCase();const target=ruleReferenceTarget(sourceView);const out=$(target.outputId);if(out)out.innerHTML='';if(!selected||!target.caseId)return;const current=sourceView==='diagnosis'?S.selectedCase:S.last;if(!current)return;const context=caseContext.capture();const result=await api('PUT',`/cases/${encodeURIComponent(target.caseId)}/card-network`,{card_network:selected,expected_revision:current.revision});if(!caseContext.isCurrent(context,false))return;if(!result.ok){if(out)out.innerHTML='<div class="error-state" role="alert">卡组织保存失败：案件版本已经变化，请刷新后重试。</div>';const input=$(sourceView==='diagnosis'?'diagnosisNetwork':'network');if(input)input.value=S.cardNetwork;return;}if(!acceptCaseSnapshot(result.data))return;if(await bindAgentCase(target.caseId,false))await analyzeCurrentCase('CASE_OPENED');}
function ruleReferencePath(caseId,cardNetwork){const id=String(caseId||'').trim();const network=String(cardNetwork||'').trim().toUpperCase();return id&&network?`/cases/${encodeURIComponent(id)}/rule-reference?card_network=${encodeURIComponent(network)}`:'';}
function ruleDetailPath(ruleVersionId){const id=String(ruleVersionId||'').trim();return id?`/rules/${encodeURIComponent(id)}`:'';}
function ruleReturnContext(sourceView='flow'){const target=ruleReferenceTarget(sourceView);return{sourceView:target.sourceView,caseId:target.caseId,cardNetwork:target.cardNetwork};}
async function resolveCaseRuleReference(sourceView='flow'){const context=caseContext.capture();const ticket=OceanRequest.begin(`case-rule:${sourceView}`);const target=ruleReferenceTarget(sourceView);const out=$(target.outputId);if(!out)return;if(!target.cardNetwork){out.innerHTML='<span class="pill p-warn">请先明确选择卡组织</span>';return;}const path=ruleReferencePath(target.caseId,target.cardNetwork);if(!path){out.innerHTML='<span class="pill p-warn">尚未选择案件</span>';return;}const result=await api('GET',path);if(!caseContext.isCurrent(context)||!OceanRequest.isLatest(ticket)||target.cardNetwork!==ruleReferenceTarget(sourceView).cardNetwork)return;const data=result.data||{};
  if(!result.ok){const message=result.status===409?'案件原因尚未确认，暂不能解析条款。':result.status===503?'规则数据库暂不可用，请稍后重试。':'条款引用暂时无法读取。';out.innerHTML=`<div class="error-state" role="alert"><strong>未解析到具体条款</strong><br>${message}</div>`;return;}
  const ref=data.rule_reference;if(data.match_status!=='EXACT_MATCH'||!ref||!ref.rule_version_id){out.innerHTML='<div class="note"><b>未解析到具体条款。</b> 当前卡组织与案件原因没有精确映射，系统没有使用相似规则代替。</div>';return;}
  out.innerHTML=`<div class="kv"><span class="k">${target.sourceView==='diagnosis'?'诊断引用':'评估引用'}</span><span><button class="tbtn" onclick="showRuleReference('${esc(ref.rule_version_id)}',ruleReturnContext('${target.sourceView}'))">${esc(ref.rule_version_id)}</button> · ${esc(ref.verification_status)} · ${esc(ref.source_section||'来源章节待核验')}</span></div><div class="helper">引用来自只读规则解析端点，与规则数据库中的版本 ID 完全一致。</div>`;}
function safeHttpUrl(value){try{const url=new URL(value);return(url.protocol==='https:'||url.protocol==='http:')?url.href:'#';}catch(error){return'#';}}
function normalizeRuleReturnContext(context){const source=context||{};return{sourceView:source.sourceView==='diagnosis'?'diagnosis':'flow',caseId:String(source.caseId||''),cardNetwork:String(source.cardNetwork||'').toUpperCase()};}
function ruleReturnButton(){const context=S.ruleReturnContext;if(!context||!context.caseId)return'';const label=context.sourceView==='diagnosis'?'返回案件诊断':'返回案件详情';return `<button class="tbtn" onclick="returnFromRuleReference()">${label}</button>`;}
function markRuleSelection(ruleVersionId){document.querySelectorAll('#ruleRows tr[data-rule-version-id]').forEach(row=>row.classList.toggle('rule-selected',row.dataset.ruleVersionId===ruleVersionId));}
async function loadRules(){const requestId=++S.rulesRequestId;S.ruleDetailRequestId++;const params=new URLSearchParams();const scheme=$('ruleScheme').value;const query=$('ruleSearch').value.trim();if(scheme)params.set('scheme',scheme);if(query)params.set('q',query);
  const suffix=params.toString()?`?${params.toString()}`:'';const result=await api('GET',`/rules${suffix}`);if(requestId!==S.rulesRequestId)return;const data=result.data||{};const detail=$('ruleDetail');
  if(!result.ok||!Array.isArray(data.items)){S.rules=[];S.currentRuleId=null;$('ruleStats').textContent='规则库暂不可用';$('ruleRows').innerHTML='<tr><td colspan="6"><div class="error-state"><strong>无法读取规则目录</strong><br>请稍后重试；页面不会回退到伪造数据。</div></td></tr>';detail.classList.remove('reference-highlight');detail.innerHTML='<div class="panel-hd"><h2>规则详情</h2></div><div class="panel-bd"><div class="error-state"><strong>规则库暂不可用</strong><br>没有使用缓存或伪造详情。</div></div>';$('crumbId').textContent='规则目录';return;}
  S.rules=data.items;$('ruleDisclaimer').textContent=data.disclaimer||$('ruleDisclaimer').textContent;$('ruleStats').textContent=`${data.total} 条 · ${data.demo_mapped} 条 Demo Mapped · ${data.scheme_count} 个卡组织 · ${data.source_document_count} 份来源`;
  $('ruleRows').innerHTML=S.rules.map(rule=>`<tr data-rule-version-id="${esc(rule.rule_version_id)}"><td><div class="rule-id">${esc(rule.rule_version_id)}</div><div class="rule-name">${esc(rule.scheme_reason_code)} · ${esc(rule.display_name)}</div></td><td>${esc(rule.scheme)}</td><td>${esc(rule.version_label||'未标定')}</td><td><span class="pill ${rule.demo_role==='DEMO_MAPPED'?'p-good':'p-mut'}">${esc(rule.demo_role)}</span></td><td><span class="pill p-acc">${esc(rule.verification_status)}</span></td><td><button class="tbtn" onclick="openRule('${esc(rule.rule_version_id)}')">查看详情</button></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty-state"><strong>没有匹配规则</strong><p>请调整卡组织或搜索条件。</p></div></td></tr>';
  if(S.currentRuleId&&S.rules.some(rule=>rule.rule_version_id===S.currentRuleId)){await openRule(S.currentRuleId);return;}S.currentRuleId=null;markRuleSelection(null);detail.classList.remove('reference-highlight');$('crumbId').textContent='规则目录';detail.innerHTML='<div class="panel-hd"><h2>规则详情</h2><span class="pill p-acc">Provenance</span></div><div class="panel-bd"><div class="empty-state"><strong>选择当前列表中的规则</strong><p>筛选已更新；旧详情已清除，避免列表与来源错配。</p></div></div>';}
async function openRule(ruleVersionId){const requestId=++S.ruleDetailRequestId;const detail=$('ruleDetail');const result=await api('GET',ruleDetailPath(ruleVersionId));if(requestId!==S.ruleDetailRequestId)return;const data=result.data||{};
  if(!result.ok){S.currentRuleId=null;markRuleSelection(null);detail.classList.remove('reference-highlight');$('crumbId').textContent='规则目录';const message=result.status===503?'规则数据库暂不可用。':'该规则版本不存在。';detail.innerHTML=`<div class="panel-hd"><h2>规则详情</h2></div><div class="panel-bd"><div class="error-state"><strong>无法读取规则详情</strong><br>${message} 旧详情已清除。</div></div>`;return;}
  S.currentRuleId=data.rule_version_id;markRuleSelection(data.rule_version_id);$('crumbId').textContent=data.rule_version_id;const requirementList=items=>(items||[]).map(item=>`<div class="requirement"><span class="seq">${esc(item.sequence)}</span><div><strong>${esc(item.description_zh)}</strong><span>${esc(item.necessity)}${item.internal_evidence_code?` · 内部映射 ${esc(item.internal_evidence_code)}`:''}</span></div></div>`).join('')||'<div class="empty">无</div>';const sourceUrl=safeHttpUrl(data.document&&data.document.source_url);
  detail.innerHTML=`<div class="panel-hd"><h2>规则详情</h2><div class="grow"></div>${ruleReturnButton()}<span class="pill p-acc">${esc(data.verification_status)}</span></div><div class="panel-bd"><div class="rule-id">${esc(data.rule_version_id)}</div><h2>${esc(data.scheme)} ${esc(data.scheme_reason_code)} · ${esc(data.display_name)}</h2><div class="row"><span class="pill ${data.demo_role==='DEMO_MAPPED'?'p-good':'p-mut'}">${esc(data.demo_role)}</span><span class="pill p-mut">${esc(data.region)}</span><span class="pill p-mut">${esc(data.version_label||'版本未标定')}</span></div><div class="rule-section"><h3>来源与适用范围</h3><div class="kv"><span class="k">文档</span><span>${esc(data.document&&data.document.title)}</span></div><div class="kv"><span class="k">章节</span><span>${esc(data.source_section||'未核验')}</span></div><div class="kv"><span class="k">生效日期</span><span>${esc(data.effective_date||'未核验')}</span></div><div class="kv"><span class="k">来源链接</span><span>${sourceUrl==='#'?esc(data.document&&data.document.source_url):`<a href="${esc(sourceUrl)}" target="_blank" rel="noopener noreferrer">打开来源文档</a>`}</span></div>${data.internal_window_days==null?'':`<div class="kv"><span class="k">内部 Demo 窗口</span><span>${esc(data.internal_window_days)} 天（非官方响应期限）</span></div>`}</div><div class="rule-section"><h3>Required Assertions</h3>${requirementList(data.assertions)}</div><div class="rule-section"><h3>卡组织打包证据摘要 · ${(data.evidence||[]).length} 项</h3>${requirementList(data.evidence)}</div><div class="rule-section"><h3>限制与免责声明</h3><div class="note">${esc(data.limitation)}<br><br>${esc(data.disclaimer)}</div></div></div>`;
  detail.classList.remove('reference-highlight');requestAnimationFrame(()=>{if(S.currentRuleId!==data.rule_version_id)return;detail.classList.add('reference-highlight');detail.focus({preventScroll:true});detail.scrollIntoView({block:'start',behavior:'auto'});setTimeout(()=>{if(S.currentRuleId===data.rule_version_id)detail.classList.remove('reference-highlight');},1600);});}
function showRuleReference(ruleVersionId,returnContext){const id=String(ruleVersionId||'').trim();if(!id)return;S.ruleReturnContext=normalizeRuleReturnContext(returnContext);S.currentRuleId=id;$('ruleSearch').value='';$('ruleScheme').value='';showView('rules');}
async function returnFromRuleReference(){const context=S.ruleReturnContext;if(!context||!context.caseId){showView('overview');return;}S.ruleReturnContext=null;const needsLoad=S.caseId!==context.caseId||!S.last;if(needsLoad)await openStoredCase(context.caseId);S.cardNetwork=context.cardNetwork;const network=$(context.sourceView==='diagnosis'?'diagnosisNetwork':'network');if(network)network.value=context.cardNetwork;if(needsLoad)return;showView(context.sourceView);}
